version: 2

project_name: mache

before:
  hooks:
    - go mod tidy

builds:
  - id: linux-build
    binary: mache
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    ldflags:
      - -s -w

  - id: macos-build
    binary: mache
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
      # Point to where the CI workflow will install fuse-t
      - CGO_CFLAGS=-I/usr/local/include/fuse-t
      - CGO_LDFLAGS=-L/usr/local/lib -lfuse-t -Wl,-rpath,/usr/local/lib
    flags:
      - -trimpath
    ldflags:
      - -s -w
    hooks:
      # Sign the binary after build
      post: codesign -s - --force --deep --entitlements entitlements.plist "{{ .Path }}"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE

brews:
  - repository:
      owner: agentic-research
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"

    # Formula name
    name: mache

    homepage: "https://github.com/agentic-research/mache"
    description: "The Graph-Native Filesystem"
    license: "Apache-2.0"

    # Test to run after installation
    test: |
      system "#{bin}/mache --version"

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
