version: '3'

vars:
  BINARY_NAME: bin/mache
  # fuse-t configuration for macOS
  FUSE_T_HEADERS: /Library/Frameworks/fuse_t.framework/Versions/Current/Headers
  FUSE_T_FRAMEWORK: /Library/Frameworks

env:
  # Set CGO flags for fuse-t on macOS (no-op on other platforms)
  CGO_CFLAGS: '{{if eq OS "darwin"}}-I{{.FUSE_T_HEADERS}}{{end}}'
  CGO_LDFLAGS: '{{if eq OS "darwin"}}-F{{.FUSE_T_FRAMEWORK}} -framework fuse_t -Wl,-rpath,{{.FUSE_T_FRAMEWORK}}{{end}}'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  check-fuse-t:
    desc: Check if fuse-t is installed (macOS only)
    silent: true
    cmds:
      - |
        if [ "$(uname)" = "Darwin" ]; then
          if [ ! -d "{{.FUSE_T_HEADERS}}" ]; then
            echo "❌ fuse-t not found. Run 'task setup' to install."
            exit 1
          else
            echo "✅ fuse-t found at {{.FUSE_T_HEADERS}}"
          fi
        else
          echo "ℹ️  fuse-t check skipped (not macOS)"
        fi

  setup:
    desc: Install system dependencies (e.g. fuse-t on macOS)
    cmds:
      - |
        if [ "$(uname)" = "Darwin" ]; then
          if [ ! -d "{{.FUSE_T_HEADERS}}" ]; then
            echo "Installing fuse-t via Homebrew..."
            brew install --cask fuse-t
          else
            echo "✅ fuse-t is already installed."
          fi
        fi

  install:
    desc: Install mache binary to $GOPATH/bin
    deps: [check-fuse-t]
    cmds:
      - go install .

  build:
    desc: Build and codesign mache (with FUSE-T network entitlements)
    deps: [check-fuse-t]
    cmds:
      - go build -o {{.BINARY_NAME}} .
      - cmd: codesign -s - --force --deep --entitlements entitlements.plist ./{{.BINARY_NAME}}
        platforms: [darwin]
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
      - entitlements.plist
    generates:
      - "{{.BINARY_NAME}}"

  test:
    desc: Run all tests
    deps: [check-fuse-t]
    cmds:
      - echo "FUSE={{.FUSE_T_HEADERS}}"
      - go test -race -gcflags=all=-d=checkptr=0 -v ./...

  test-coverage:
    desc: Run tests with coverage
    cmds:
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated at coverage.html"

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  fmt:
    desc: Format code with gofumpt
    cmds:
      - gofumpt -w -extra .

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f {{.BINARY_NAME}}
      - rm -f coverage.out coverage.html

  validate:
    desc: Validate example schemas against synthetic SQLite fixtures (no FUSE required)
    cmds:
      - go test -v -run 'TestEngine_IngestSQLite' ./internal/ingest/

  test-go-schema:
    desc: Validate Go schema by ingesting mache's own source tree (self-hosting smoke test)
    deps: [build]
    cmds:
      - go test -v -run 'TestEngine_IngestTreeSitter_Go' ./internal/ingest/

  fuzz-gen:
    desc: Generate a new "Fuzz-Mutate-Repair" task by breaking a target
    dir: tools/fuzz-gen
    cmds:
      - go run main.go -file target/parser.go -target FuzzParseToken

  check:
    desc: Run all checks (fmt, vet, lint, test, validate)
    cmds:
      - task: fmt
      - task: vet
      - task: lint
      - task: test
      - task: validate
