package mcpserve

import (
	"bytes"
	"context"
	"database/sql"
	"strings"
	"testing"

	"github.com/agentic-research/mache/graph"
	"github.com/agentic-research/mache/internal/fixturedb"
	"github.com/agentic-research/mache/internal/smells"
	"github.com/agentic-research/mache/internal/testutil"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// runSmellCLIJSON runs one rule through the find-smells CLI engine
// (smells.RunFindSmells — the same code path the flags drive) and returns its
// JSON payload. The Encoder's trailing newline is stream framing, not payload,
// so it is trimmed — everything else must match the MCP bytes exactly.
func runSmellCLIJSON(t *testing.T, dbPath, rule string) string {
	t.Helper()
	var buf bytes.Buffer
	code, err := smells.RunFindSmells(smells.FindSmellsOptions{
		DB: dbPath, Rule: rule, Format: "json", Limit: 200,
		Out: &buf, Err: &buf,
	})
	require.NoError(t, err)
	require.Equal(t, 0, code, "CLI run must succeed: %s", buf.String())
	return strings.TrimRight(buf.String(), "\n")
}

// writeSmellParityFixture builds the dead-code parity fixture with
// internal/fixturedb (Standalone = mache's projection shape): Live defined
// and referenced, Dead defined and unreferenced. fixturedb, not hand-written
// DDL — the LLO boundary gate rejects hand-built node_defs/node_refs because
// the DDL a fixture happens to type silently selects which v_refs arm the
// rule under test runs (mache-7555da).
func writeSmellParityFixture(t *testing.T) string {
	t.Helper()
	path, _ := fixturedb.New(t, fixturedb.Standalone).
		Construct("pkg/Live", fixturedb.Where{Source: "live.go"}).
		Construct("pkg/Caller", fixturedb.Where{Source: "caller.go"}).
		Construct("pkg/Dead", fixturedb.Where{Source: "dead.go"}).
		Def("Live", "pkg/Live", "").
		Def("Dead", "pkg/Dead", "").
		Ref("Live", "pkg/Caller", "", "").
		Build()
	return path
}

// runSmellMCPJSON runs the same rule through the find_smells MCP handler,
// against a *lazyGraph — the graph a handler actually holds in serve mode,
// not the backend underneath it.
func runSmellMCPJSON(t *testing.T, dbPath, rule string) string {
	t.Helper()
	db, err := sql.Open("sqlite", dbPath)
	require.NoError(t, err)
	t.Cleanup(func() { _ = db.Close() })
	// Same single-connection pinning the CLI applies: the TEMP tables that
	// ensureSmellQueryContext creates are per-connection, so a pool that hands
	// out a second connection loses them non-deterministically.
	db.SetMaxOpenConns(1)

	// testutil.SmellTestGraph is the serve-mode backend shape this package already
	// has: a graph.Graph carrying a SQL handle plus the .db path that opts it
	// into capnp readthrough. Setting path is what makes this test meaningful
	// — an unset path would silently reproduce the very defect under test.
	lg := newTestLazyGraph(&testutil.SmellTestGraph{
		MemoryStore: graph.NewMemoryStore(), DB: db, Path: dbPath,
	}, "")

	res, err := smells.MakeFindSmellsHandler(lg)(context.Background(), testutil.MakeRequest(map[string]any{
		"rule": rule, "limit": float64(200),
	}))
	require.NoError(t, err)
	require.False(t, res.IsError, "MCP run must succeed: %s", testutil.ResultText(t, res))
	return testutil.ResultText(t, res)
}

// TestFindSmells_MCPAndCLI_ByteForByteParity is the standing proof that the
// two consumers of the smell engine give the same answer over the same .db.
//
// That property is load-bearing rather than aesthetic: the committed smell
// baseline is generated by the CLI, and the ratchet only means anything to an
// agent calling the MCP tool if both see the same findings. The two had
// already drifted in two independent ways — a capability the MCP path could
// not reach, and an envelope each path built for itself.
func TestFindSmells_MCPAndCLI_ByteForByteParity(t *testing.T) {
	// A rule with findings: the shared path must agree on content AND shape.
	t.Run("with findings", func(t *testing.T) {
		dbPath := writeSmellParityFixture(t)

		cliOut := runSmellCLIJSON(t, dbPath, "dead_code")
		mcpOut := runSmellMCPJSON(t, dbPath, "dead_code")

		require.Contains(t, cliOut, "pkg/Dead", "fixture must actually produce a finding, or this proves nothing")
		assert.Equal(t, cliOut, mcpOut, "same rules, same .db — the bytes must match")
	})

	// The discriminating case. A sibling .bindings.capnp record marking
	// pkg/Dead as referenced reaches the rule only through DBPath ->
	// LoadCapnpBindings -> the _capnp_binding_refs arm of v_refs. Before
	// lazyGraph forwarded DBPath, the CLI saw this record and the MCP handler
	// did not, so the two paths disagreed about whether pkg/Dead was dead.
	t.Run("capnp binding is visible to both paths", func(t *testing.T) {
		dbPath := writeSmellParityFixture(t)
		testutil.WriteBindingLogForTest(t, dbPath,
			"pkg/Dead", "Dead", "pkg/Caller", "file:///pkg/caller.go")

		cliOut := runSmellCLIJSON(t, dbPath, "dead_code")
		mcpOut := runSmellMCPJSON(t, dbPath, "dead_code")

		assert.Equal(t, cliOut, mcpOut, "the capnp binding log must be reachable from BOTH paths")
		assert.NotContains(t, mcpOut, "pkg/Dead",
			"a capnp binding referencing pkg/Dead must retire the dead_code finding; "+
				"if it still fires, the MCP path is not reading the sibling log")
	})

	// A clean run is where the envelope divergence lived: a nil finding set
	// marshals to `null`, and only the CLI normalized it to `[]`.
	t.Run("clean run emits the same empty shape", func(t *testing.T) {
		dbPath := writeSmellParityFixture(t)

		cliOut := runSmellCLIJSON(t, dbPath, "duplicate_definitions")
		mcpOut := runSmellMCPJSON(t, dbPath, "duplicate_definitions")

		assert.Equal(t, cliOut, mcpOut)
		assert.Contains(t, cliOut, `"findings": []`,
			`zero findings must serialize as [] on both paths, never null`)
	})
}
