// Code generated by capnpc-go. DO NOT EDIT.

package bindings

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
)

type BindingRecord capnp.Struct

// BindingRecord_TypeID is the unique identifier for the type BindingRecord.
const BindingRecord_TypeID = 0xb25434baab461394

func NewBindingRecord(s *capnp.Segment) (BindingRecord, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 7})
	return BindingRecord(st), err
}

func NewRootBindingRecord(s *capnp.Segment) (BindingRecord, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 7})
	return BindingRecord(st), err
}

func ReadRootBindingRecord(msg *capnp.Message) (BindingRecord, error) {
	root, err := msg.Root()
	return BindingRecord(root.Struct()), err
}

func (s BindingRecord) String() string {
	str, _ := text.Marshal(0xb25434baab461394, capnp.Struct(s))
	return str
}

func (s BindingRecord) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (BindingRecord) DecodeFromPtr(p capnp.Ptr) BindingRecord {
	return BindingRecord(capnp.Struct{}.DecodeFromPtr(p))
}

func (s BindingRecord) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s BindingRecord) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s BindingRecord) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s BindingRecord) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s BindingRecord) TargetNodeId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s BindingRecord) HasTargetNodeId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s BindingRecord) TargetNodeIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s BindingRecord) SetTargetNodeId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s BindingRecord) RefToken() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s BindingRecord) HasRefToken() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s BindingRecord) RefTokenBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s BindingRecord) SetRefToken(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s BindingRecord) ConstructNodeId() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s BindingRecord) HasConstructNodeId() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s BindingRecord) ConstructNodeIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s BindingRecord) SetConstructNodeId(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s BindingRecord) RefSiteNodeId() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s BindingRecord) HasRefSiteNodeId() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s BindingRecord) RefSiteNodeIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s BindingRecord) SetRefSiteNodeId(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s BindingRecord) RefUri() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s BindingRecord) HasRefUri() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s BindingRecord) RefUriBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s BindingRecord) SetRefUri(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s BindingRecord) RefRange() (Range, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return Range(p.Struct()), err
}

func (s BindingRecord) HasRefRange() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s BindingRecord) SetRefRange(v Range) error {
	return capnp.Struct(s).SetPtr(5, capnp.Struct(v).ToPtr())
}

// NewRefRange sets the refRange field to a newly
// allocated Range struct, preferring placement in s's segment.
func (s BindingRecord) NewRefRange() (Range, error) {
	ss, err := NewRange(capnp.Struct(s).Segment())
	if err != nil {
		return Range{}, err
	}
	err = capnp.Struct(s).SetPtr(5, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s BindingRecord) ParseGen() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s BindingRecord) SetParseGen(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s BindingRecord) Qualifier() (string, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.Text(), err
}

func (s BindingRecord) HasQualifier() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s BindingRecord) QualifierBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.TextBytes(), err
}

func (s BindingRecord) SetQualifier(v string) error {
	return capnp.Struct(s).SetText(6, v)
}

// BindingRecord_List is a list of BindingRecord.
type BindingRecord_List = capnp.StructList[BindingRecord]

// NewBindingRecord creates a new list of BindingRecord.
func NewBindingRecord_List(s *capnp.Segment, sz int32) (BindingRecord_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 7}, sz)
	return capnp.StructList[BindingRecord](l), err
}

// BindingRecord_Future is a wrapper for a BindingRecord promised by a client call.
type BindingRecord_Future struct{ *capnp.Future }

func (f BindingRecord_Future) Struct() (BindingRecord, error) {
	p, err := f.Future.Ptr()
	return BindingRecord(p.Struct()), err
}

func (p BindingRecord_Future) RefRange() Range_Future {
	return Range_Future{Future: p.Future.Field(5, nil)}
}
