// Code generated by capnpc-go. DO NOT EDIT.

package bindings

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
)

type Position capnp.Struct

// Position_TypeID is the unique identifier for the type Position.
const Position_TypeID = 0xb15cd2b768ffe71c

func NewPosition(s *capnp.Segment) (Position, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return Position(st), err
}

func NewRootPosition(s *capnp.Segment) (Position, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return Position(st), err
}

func ReadRootPosition(msg *capnp.Message) (Position, error) {
	root, err := msg.Root()
	return Position(root.Struct()), err
}

func (s Position) String() string {
	str, _ := text.Marshal(0xb15cd2b768ffe71c, capnp.Struct(s))
	return str
}

func (s Position) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Position) DecodeFromPtr(p capnp.Ptr) Position {
	return Position(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Position) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Position) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Position) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Position) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s Position) Line() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s Position) SetLine(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s Position) Column() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s Position) SetColumn(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

func (s Position) Byte() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s Position) SetByte(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

// Position_List is a list of Position.
type Position_List = capnp.StructList[Position]

// NewPosition creates a new list of Position.
func NewPosition_List(s *capnp.Segment, sz int32) (Position_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[Position](l), err
}

// Position_Future is a wrapper for a Position promised by a client call.
type Position_Future struct{ *capnp.Future }

func (f Position_Future) Struct() (Position, error) {
	p, err := f.Future.Ptr()
	return Position(p.Struct()), err
}

type Range capnp.Struct

// Range_TypeID is the unique identifier for the type Range.
const Range_TypeID = 0xb70d94b5bbba004a

func NewRange(s *capnp.Segment) (Range, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Range(st), err
}

func NewRootRange(s *capnp.Segment) (Range, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Range(st), err
}

func ReadRootRange(msg *capnp.Message) (Range, error) {
	root, err := msg.Root()
	return Range(root.Struct()), err
}

func (s Range) String() string {
	str, _ := text.Marshal(0xb70d94b5bbba004a, capnp.Struct(s))
	return str
}

func (s Range) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Range) DecodeFromPtr(p capnp.Ptr) Range {
	return Range(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Range) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Range) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Range) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Range) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s Range) Start() (Position, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Position(p.Struct()), err
}

func (s Range) HasStart() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Range) SetStart(v Position) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewStart sets the start field to a newly
// allocated Position struct, preferring placement in s's segment.
func (s Range) NewStart() (Position, error) {
	ss, err := NewPosition(capnp.Struct(s).Segment())
	if err != nil {
		return Position{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Range) End() (Position, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return Position(p.Struct()), err
}

func (s Range) HasEnd() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Range) SetEnd(v Position) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewEnd sets the end field to a newly
// allocated Position struct, preferring placement in s's segment.
func (s Range) NewEnd() (Position, error) {
	ss, err := NewPosition(capnp.Struct(s).Segment())
	if err != nil {
		return Position{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Range_List is a list of Range.
type Range_List = capnp.StructList[Range]

// NewRange creates a new list of Range.
func NewRange_List(s *capnp.Segment, sz int32) (Range_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Range](l), err
}

// Range_Future is a wrapper for a Range promised by a client call.
type Range_Future struct{ *capnp.Future }

func (f Range_Future) Struct() (Range, error) {
	p, err := f.Future.Ptr()
	return Range(p.Struct()), err
}

func (p Range_Future) Start() Position_Future {
	return Position_Future{Future: p.Future.Field(0, nil)}
}

func (p Range_Future) End() Position_Future {
	return Position_Future{Future: p.Future.Field(1, nil)}
}

type Hash capnp.Struct

// Hash_TypeID is the unique identifier for the type Hash.
const Hash_TypeID = 0xec0494688f0a29ca

func NewHash(s *capnp.Segment) (Hash, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Hash(st), err
}

func NewRootHash(s *capnp.Segment) (Hash, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Hash(st), err
}

func ReadRootHash(msg *capnp.Message) (Hash, error) {
	root, err := msg.Root()
	return Hash(root.Struct()), err
}

func (s Hash) String() string {
	str, _ := text.Marshal(0xec0494688f0a29ca, capnp.Struct(s))
	return str
}

func (s Hash) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Hash) DecodeFromPtr(p capnp.Ptr) Hash {
	return Hash(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Hash) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Hash) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Hash) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Hash) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s Hash) Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Hash) HasBytes() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Hash) SetBytes(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// Hash_List is a list of Hash.
type Hash_List = capnp.StructList[Hash]

// NewHash creates a new list of Hash.
func NewHash_List(s *capnp.Segment, sz int32) (Hash_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Hash](l), err
}

// Hash_Future is a wrapper for a Hash promised by a client call.
type Hash_Future struct{ *capnp.Future }

func (f Hash_Future) Struct() (Hash, error) {
	p, err := f.Future.Ptr()
	return Hash(p.Struct()), err
}

type NodeRef capnp.Struct

// NodeRef_TypeID is the unique identifier for the type NodeRef.
const NodeRef_TypeID = 0xd0d235685d85719f

func NewNodeRef(s *capnp.Segment) (NodeRef, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return NodeRef(st), err
}

func NewRootNodeRef(s *capnp.Segment) (NodeRef, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return NodeRef(st), err
}

func ReadRootNodeRef(msg *capnp.Message) (NodeRef, error) {
	root, err := msg.Root()
	return NodeRef(root.Struct()), err
}

func (s NodeRef) String() string {
	str, _ := text.Marshal(0xd0d235685d85719f, capnp.Struct(s))
	return str
}

func (s NodeRef) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (NodeRef) DecodeFromPtr(p capnp.Ptr) NodeRef {
	return NodeRef(capnp.Struct{}.DecodeFromPtr(p))
}

func (s NodeRef) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s NodeRef) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s NodeRef) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s NodeRef) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s NodeRef) SourceId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s NodeRef) HasSourceId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s NodeRef) SourceIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s NodeRef) SetSourceId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s NodeRef) NodeId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s NodeRef) HasNodeId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s NodeRef) NodeIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s NodeRef) SetNodeId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s NodeRef) Range() (Range, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return Range(p.Struct()), err
}

func (s NodeRef) HasRange() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s NodeRef) SetRange(v Range) error {
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewRange sets the range field to a newly
// allocated Range struct, preferring placement in s's segment.
func (s NodeRef) NewRange() (Range, error) {
	ss, err := NewRange(capnp.Struct(s).Segment())
	if err != nil {
		return Range{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

// NodeRef_List is a list of NodeRef.
type NodeRef_List = capnp.StructList[NodeRef]

// NewNodeRef creates a new list of NodeRef.
func NewNodeRef_List(s *capnp.Segment, sz int32) (NodeRef_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3}, sz)
	return capnp.StructList[NodeRef](l), err
}

// NodeRef_Future is a wrapper for a NodeRef promised by a client call.
type NodeRef_Future struct{ *capnp.Future }

func (f NodeRef_Future) Struct() (NodeRef, error) {
	p, err := f.Future.Ptr()
	return NodeRef(p.Struct()), err
}

func (p NodeRef_Future) Range() Range_Future {
	return Range_Future{Future: p.Future.Field(2, nil)}
}

const schema_b0c0debaadc0deb0 = "x\xdad\x93AH\x1cW\x1c\xc6\xff\xdf{3\xbbk" +
	"\xd9\xed\xee0s,l)\x15\xb4\xa0Xk\xa1\x08e" +
	"\xa5\xd4VE\x17\xdf\xae\x85\x1e\xda\xc38\xfbvwZ" +
	"\x9d\xd1\xd9Y\xa4\xd7\x82\x87BK\xa1\xd8\x8b\x04B\x0e" +
	"9$!D\x85 \x98\x8b\x97\x10\xc8\xc9\x98K\x02A" +
	"\x92\x10H\x02^\x02\x06r\x88Lx\xbb\xec\xee\xa8\xb7" +
	"\xf9\xff\xf9\xf8\x7f\xbf\xf9\xe6\x9b\x91\xff1\xa1}\x99Y" +
	"\xe3\xc4\xc4\x80\x9e\x88>y\x19\xd5w\x0f\x7f\xd9&\x91" +
	"\x01\x8b\xb6\x8e\xf6o\xee\x1d\xedo\x91\x96$2\xaf`" +
	"\xc7\xbc\x06\xf5t\x15\xb7\x08\xd1\x86\xf9\xc3\x8d\xbd\xb1\x85" +
	"\x1d\x12\x1f\x03\xd1\xe6\xe8\xf6\xdd\x87\x7f\xa7/\x91\x9eT" +
	"\x92o\xd9ss\x9a%\x89\xbe\x9ad\xf7@8\x9d\xd9" +
	"\xbbs{#\xb3kd\xd0;\xab+\x81\xd9\xafm\x9a" +
	"C-\x87Am\x8d\x10]^]\xff\xb5\xfe\xf5\xe1\x01" +
	"\x9d\xd5r\xa5X\xd7\xae\x9b\xff\xb4\xb4\x7fi\x8a\xe1\xfe" +
	"\xe0G\xff\xd67\xb4\xe3s\xda\x16e\xbf\xfe\x9f9\xa4" +
	"\xb7\xee\xea\x05\xfa&r\xfc\xe5e\xdf\x1bv`\xafx" +
	"+\xe3\xf3~#\xef\x86\xae\xef\xcd\x03\"\xcd5\"\x0d" +
	"D\xc6\xe4\x17Db\x82C\xcc2\x18\x80\x05\xb5\x9c\x1e" +
	"'\x12\xdfs\x88y\x06\x83\xc1\x02#2\xe6\x94r\x8a" +
	"C,0d\x97\\O\"E\x0c)B\xc1\xf1\x97\x9a" +
	"\xcb^g\xcc.\xfe\x11J\xf4\x11C\x1f!Zt\xbd" +
	"\x8a\xeb\xd5\x86\x99\xd3\xa2\xf8\xae=\x96\xa4\x93\xf4\x83\x8a" +
	"B\xf9\xb4\x8b\xf2\xe07\"q\xc0!\x9e\xc4P\x1e\xcf" +
	"\x10\x89G\x1c\xe2\x85Bam\x94g\x7f\x12\x89\xa7\x1c" +
	"\xe2\x98\xc1\xe0\xdc\x02'2^\x07D\xe2\x15\x878a" +
	"04\xcd\x82Fd\xbcQor\xcc!\xde1\x18\xba" +
	"nA'2\xde\xaa\x9b'\x1c%0 a!Ad" +
	"\x9c\xaa\xdd{\x8er\x0a\x0cF2a\xb5\"\xd5Q\"" +
	"*k\xe0(\xe7\xc0\x10\x85vP\x93a\xd1\xa7lE" +
	"NW\x90&\x864!\x0adu\xc1\xff]zD\xd4" +
	"\xdd9\xbe\xd7\x08\x83\xa6\x83\xb0\xe8+1\xc5\xd5e7" +
	"\x94E\xca\xfb\xf1+\x85@V\x7f\x0a\xdc\xb8\xacd{" +
	"5\xa9\x8e\xe6:u\" G\x88V\xec\xa0!\x7fl" +
	"\x1bv\x92^m\xdaKn\xd5\x95\x84 \x06\x11\xaf@" +
	"\xc9\xf6xM\xaa\xd0S\xdd\xd0\x07G\x89\xc4\xe7\x1cb" +
	"$\x16\xfa\xd0gDb\x80C\x8c1\xe4\x1b\xa1\x1d\x84" +
	"\xc8\xf5~\x956CRz\x95\x8b\xdbs\x8eE\xbf\x92" +
	"\x95%Y=\xd7\xb9\x99X\xbd:\x9es\xe3\xbdzu" +
	"?\xb4Pt\xb3\x1c\xe2g\x86\xa8\xe17\x03G%\xd9" +
	"K\xb9\xe0\x9d\x890\x1f\xa8\xc0.\xa4u\x96i\xcan" +
	"\xa0\xae\x80\xb4.PF\xd9\xa48\x84\xc5\x90W\xf5m" +
	" C\x0c\x19\xc2\x87\x00\x00\x00\xff\xff\x0fz\xfa\xad"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_b0c0debaadc0deb0,
		Nodes: []uint64{
			0xb15cd2b768ffe71c,
			0xb25434baab461394,
			0xb70d94b5bbba004a,
			0xd0d235685d85719f,
			0xec0494688f0a29ca,
		},
		Compressed: true,
	})
}
