// Code generated by capnpc-go. DO NOT EDIT.

package schema

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
)

type Node capnp.Struct

// Node_TypeID is the unique identifier for the type Node.
const Node_TypeID = 0x8788a694e7d0c9f7

func NewNode(s *capnp.Segment) (Node, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 4})
	return Node(st), err
}

func NewRootNode(s *capnp.Segment) (Node, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 4})
	return Node(st), err
}

func ReadRootNode(msg *capnp.Message) (Node, error) {
	root, err := msg.Root()
	return Node(root.Struct()), err
}

func (s Node) String() string {
	str, _ := text.Marshal(0x8788a694e7d0c9f7, capnp.Struct(s))
	return str
}

func (s Node) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Node) DecodeFromPtr(p capnp.Ptr) Node {
	return Node(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Node) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Node) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Node) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Node) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s Node) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Node) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Node) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Node) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Node) ParentId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Node) HasParentId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Node) ParentIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Node) SetParentId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Node) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Node) HasName() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Node) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Node) SetName(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s Node) Kind() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s Node) SetKind(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

func (s Node) Size() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s Node) SetSize(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s Node) Record() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s Node) HasRecord() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Node) RecordBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s Node) SetRecord(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

// Node_List is a list of Node.
type Node_List = capnp.StructList[Node]

// NewNode creates a new list of Node.
func NewNode_List(s *capnp.Segment, sz int32) (Node_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 4}, sz)
	return capnp.StructList[Node](l), err
}

// Node_Future is a wrapper for a Node promised by a client call.
type Node_Future struct{ *capnp.Future }

func (f Node_Future) Struct() (Node, error) {
	p, err := f.Future.Ptr()
	return Node(p.Struct()), err
}

type Ref capnp.Struct

// Ref_TypeID is the unique identifier for the type Ref.
const Ref_TypeID = 0x9d12d8051cf589b2

func NewRef(s *capnp.Segment) (Ref, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Ref(st), err
}

func NewRootRef(s *capnp.Segment) (Ref, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Ref(st), err
}

func ReadRootRef(msg *capnp.Message) (Ref, error) {
	root, err := msg.Root()
	return Ref(root.Struct()), err
}

func (s Ref) String() string {
	str, _ := text.Marshal(0x9d12d8051cf589b2, capnp.Struct(s))
	return str
}

func (s Ref) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Ref) DecodeFromPtr(p capnp.Ptr) Ref {
	return Ref(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Ref) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Ref) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Ref) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Ref) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s Ref) NodeId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Ref) HasNodeId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Ref) NodeIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Ref) SetNodeId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Ref) SourceId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Ref) HasSourceId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Ref) SourceIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Ref) SetSourceId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// Ref_List is a list of Ref.
type Ref_List = capnp.StructList[Ref]

// NewRef creates a new list of Ref.
func NewRef_List(s *capnp.Segment, sz int32) (Ref_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Ref](l), err
}

// Ref_Future is a wrapper for a Ref promised by a client call.
type Ref_Future struct{ *capnp.Future }

func (f Ref_Future) Struct() (Ref, error) {
	p, err := f.Future.Ptr()
	return Ref(p.Struct()), err
}

type ParseStats capnp.Struct

// ParseStats_TypeID is the unique identifier for the type ParseStats.
const ParseStats_TypeID = 0xe26eae3a020ab758

func NewParseStats(s *capnp.Segment) (ParseStats, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 1})
	return ParseStats(st), err
}

func NewRootParseStats(s *capnp.Segment) (ParseStats, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 1})
	return ParseStats(st), err
}

func ReadRootParseStats(msg *capnp.Message) (ParseStats, error) {
	root, err := msg.Root()
	return ParseStats(root.Struct()), err
}

func (s ParseStats) String() string {
	str, _ := text.Marshal(0xe26eae3a020ab758, capnp.Struct(s))
	return str
}

func (s ParseStats) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ParseStats) DecodeFromPtr(p capnp.Ptr) ParseStats {
	return ParseStats(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ParseStats) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s ParseStats) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ParseStats) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ParseStats) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s ParseStats) Parsed() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s ParseStats) SetParsed(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s ParseStats) Unchanged() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s ParseStats) SetUnchanged(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s ParseStats) Deleted() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s ParseStats) SetDeleted(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s ParseStats) Errors() uint64 {
	return capnp.Struct(s).Uint64(24)
}

func (s ParseStats) SetErrors(v uint64) {
	capnp.Struct(s).SetUint64(24, v)
}

func (s ParseStats) ChangedFiles() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.TextList(p.List()), err
}

func (s ParseStats) HasChangedFiles() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ParseStats) SetChangedFiles(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewChangedFiles sets the changedFiles field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s ParseStats) NewChangedFiles(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// ParseStats_List is a list of ParseStats.
type ParseStats_List = capnp.StructList[ParseStats]

// NewParseStats creates a new list of ParseStats.
func NewParseStats_List(s *capnp.Segment, sz int32) (ParseStats_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 32, PointerCount: 1}, sz)
	return capnp.StructList[ParseStats](l), err
}

// ParseStats_Future is a wrapper for a ParseStats promised by a client call.
type ParseStats_Future struct{ *capnp.Future }

func (f ParseStats_Future) Struct() (ParseStats, error) {
	p, err := f.Future.Ptr()
	return ParseStats(p.Struct()), err
}

type EnrichmentStats capnp.Struct

// EnrichmentStats_TypeID is the unique identifier for the type EnrichmentStats.
const EnrichmentStats_TypeID = 0xde3056d78221ed35

func NewEnrichmentStats(s *capnp.Segment) (EnrichmentStats, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return EnrichmentStats(st), err
}

func NewRootEnrichmentStats(s *capnp.Segment) (EnrichmentStats, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return EnrichmentStats(st), err
}

func ReadRootEnrichmentStats(msg *capnp.Message) (EnrichmentStats, error) {
	root, err := msg.Root()
	return EnrichmentStats(root.Struct()), err
}

func (s EnrichmentStats) String() string {
	str, _ := text.Marshal(0xde3056d78221ed35, capnp.Struct(s))
	return str
}

func (s EnrichmentStats) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EnrichmentStats) DecodeFromPtr(p capnp.Ptr) EnrichmentStats {
	return EnrichmentStats(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EnrichmentStats) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s EnrichmentStats) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EnrichmentStats) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EnrichmentStats) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s EnrichmentStats) PassName() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s EnrichmentStats) HasPassName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EnrichmentStats) PassNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s EnrichmentStats) SetPassName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s EnrichmentStats) FilesProcessed() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EnrichmentStats) SetFilesProcessed(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s EnrichmentStats) ItemsAdded() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s EnrichmentStats) SetItemsAdded(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s EnrichmentStats) DurationMs() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s EnrichmentStats) SetDurationMs(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

// EnrichmentStats_List is a list of EnrichmentStats.
type EnrichmentStats_List = capnp.StructList[EnrichmentStats]

// NewEnrichmentStats creates a new list of EnrichmentStats.
func NewEnrichmentStats_List(s *capnp.Segment, sz int32) (EnrichmentStats_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1}, sz)
	return capnp.StructList[EnrichmentStats](l), err
}

// EnrichmentStats_Future is a wrapper for a EnrichmentStats promised by a client call.
type EnrichmentStats_Future struct{ *capnp.Future }

func (f EnrichmentStats_Future) Struct() (EnrichmentStats, error) {
	p, err := f.Future.Ptr()
	return EnrichmentStats(p.Struct()), err
}

type Event capnp.Struct

// Event_TypeID is the unique identifier for the type Event.
const Event_TypeID = 0xb8a347db1f686319

func NewEvent(s *capnp.Segment) (Event, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return Event(st), err
}

func NewRootEvent(s *capnp.Segment) (Event, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return Event(st), err
}

func ReadRootEvent(msg *capnp.Message) (Event, error) {
	root, err := msg.Root()
	return Event(root.Struct()), err
}

func (s Event) String() string {
	str, _ := text.Marshal(0xb8a347db1f686319, capnp.Struct(s))
	return str
}

func (s Event) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Event) DecodeFromPtr(p capnp.Ptr) Event {
	return Event(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Event) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Event) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Event) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Event) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s Event) Seq() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Event) SetSeq(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s Event) Topic() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Event) HasTopic() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Event) TopicBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Event) SetTopic(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Event) Source() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Event) HasSource() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Event) SourceBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Event) SetSource(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Event) Data() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Event) HasData() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Event) DataBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Event) SetData(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

// Event_List is a list of Event.
type Event_List = capnp.StructList[Event]

// NewEvent creates a new list of Event.
func NewEvent_List(s *capnp.Segment, sz int32) (Event_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3}, sz)
	return capnp.StructList[Event](l), err
}

// Event_Future is a wrapper for a Event promised by a client call.
type Event_Future struct{ *capnp.Future }

func (f Event_Future) Struct() (Event, error) {
	p, err := f.Future.Ptr()
	return Event(p.Struct()), err
}

type QueryRow capnp.Struct

// QueryRow_TypeID is the unique identifier for the type QueryRow.
const QueryRow_TypeID = 0xf3bbef28c2f00292

func NewQueryRow(s *capnp.Segment) (QueryRow, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return QueryRow(st), err
}

func NewRootQueryRow(s *capnp.Segment) (QueryRow, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return QueryRow(st), err
}

func ReadRootQueryRow(msg *capnp.Message) (QueryRow, error) {
	root, err := msg.Root()
	return QueryRow(root.Struct()), err
}

func (s QueryRow) String() string {
	str, _ := text.Marshal(0xf3bbef28c2f00292, capnp.Struct(s))
	return str
}

func (s QueryRow) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (QueryRow) DecodeFromPtr(p capnp.Ptr) QueryRow {
	return QueryRow(capnp.Struct{}.DecodeFromPtr(p))
}

func (s QueryRow) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s QueryRow) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s QueryRow) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s QueryRow) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s QueryRow) Values() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.TextList(p.List()), err
}

func (s QueryRow) HasValues() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s QueryRow) SetValues(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewValues sets the values field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s QueryRow) NewValues(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// QueryRow_List is a list of QueryRow.
type QueryRow_List = capnp.StructList[QueryRow]

// NewQueryRow creates a new list of QueryRow.
func NewQueryRow_List(s *capnp.Segment, sz int32) (QueryRow_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[QueryRow](l), err
}

// QueryRow_Future is a wrapper for a QueryRow promised by a client call.
type QueryRow_Future struct{ *capnp.Future }

func (f QueryRow_Future) Struct() (QueryRow, error) {
	p, err := f.Future.Ptr()
	return QueryRow(p.Struct()), err
}

type StatusResponse capnp.Struct

// StatusResponse_TypeID is the unique identifier for the type StatusResponse.
const StatusResponse_TypeID = 0xc24dfe5c0df4dc8c

func NewStatusResponse(s *capnp.Segment) (StatusResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return StatusResponse(st), err
}

func NewRootStatusResponse(s *capnp.Segment) (StatusResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return StatusResponse(st), err
}

func ReadRootStatusResponse(msg *capnp.Message) (StatusResponse, error) {
	root, err := msg.Root()
	return StatusResponse(root.Struct()), err
}

func (s StatusResponse) String() string {
	str, _ := text.Marshal(0xc24dfe5c0df4dc8c, capnp.Struct(s))
	return str
}

func (s StatusResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (StatusResponse) DecodeFromPtr(p capnp.Ptr) StatusResponse {
	return StatusResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s StatusResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s StatusResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s StatusResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s StatusResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s StatusResponse) Ok() bool {
	return capnp.Struct(s).Bit(0)
}

func (s StatusResponse) SetOk(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s StatusResponse) Generation() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s StatusResponse) SetGeneration(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s StatusResponse) ArenaPath() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s StatusResponse) HasArenaPath() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s StatusResponse) ArenaPathBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s StatusResponse) SetArenaPath(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s StatusResponse) ArenaSize() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s StatusResponse) SetArenaSize(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

// StatusResponse_List is a list of StatusResponse.
type StatusResponse_List = capnp.StructList[StatusResponse]

// NewStatusResponse creates a new list of StatusResponse.
func NewStatusResponse_List(s *capnp.Segment, sz int32) (StatusResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1}, sz)
	return capnp.StructList[StatusResponse](l), err
}

// StatusResponse_Future is a wrapper for a StatusResponse promised by a client call.
type StatusResponse_Future struct{ *capnp.Future }

func (f StatusResponse_Future) Struct() (StatusResponse, error) {
	p, err := f.Future.Ptr()
	return StatusResponse(p.Struct()), err
}

type ReparseRequest capnp.Struct

// ReparseRequest_TypeID is the unique identifier for the type ReparseRequest.
const ReparseRequest_TypeID = 0x8a447bf6ec09fbf7

func NewReparseRequest(s *capnp.Segment) (ReparseRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return ReparseRequest(st), err
}

func NewRootReparseRequest(s *capnp.Segment) (ReparseRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return ReparseRequest(st), err
}

func ReadRootReparseRequest(msg *capnp.Message) (ReparseRequest, error) {
	root, err := msg.Root()
	return ReparseRequest(root.Struct()), err
}

func (s ReparseRequest) String() string {
	str, _ := text.Marshal(0x8a447bf6ec09fbf7, capnp.Struct(s))
	return str
}

func (s ReparseRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ReparseRequest) DecodeFromPtr(p capnp.Ptr) ReparseRequest {
	return ReparseRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ReparseRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s ReparseRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ReparseRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ReparseRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s ReparseRequest) Source() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ReparseRequest) HasSource() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ReparseRequest) SourceBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ReparseRequest) SetSource(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ReparseRequest) Lang() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ReparseRequest) HasLang() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ReparseRequest) LangBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ReparseRequest) SetLang(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// ReparseRequest_List is a list of ReparseRequest.
type ReparseRequest_List = capnp.StructList[ReparseRequest]

// NewReparseRequest creates a new list of ReparseRequest.
func NewReparseRequest_List(s *capnp.Segment, sz int32) (ReparseRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[ReparseRequest](l), err
}

// ReparseRequest_Future is a wrapper for a ReparseRequest promised by a client call.
type ReparseRequest_Future struct{ *capnp.Future }

func (f ReparseRequest_Future) Struct() (ReparseRequest, error) {
	p, err := f.Future.Ptr()
	return ReparseRequest(p.Struct()), err
}

type ReparseResponse capnp.Struct

// ReparseResponse_TypeID is the unique identifier for the type ReparseResponse.
const ReparseResponse_TypeID = 0xc927f717ca8760b9

func NewReparseResponse(s *capnp.Segment) (ReparseResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return ReparseResponse(st), err
}

func NewRootReparseResponse(s *capnp.Segment) (ReparseResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return ReparseResponse(st), err
}

func ReadRootReparseResponse(msg *capnp.Message) (ReparseResponse, error) {
	root, err := msg.Root()
	return ReparseResponse(root.Struct()), err
}

func (s ReparseResponse) String() string {
	str, _ := text.Marshal(0xc927f717ca8760b9, capnp.Struct(s))
	return str
}

func (s ReparseResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ReparseResponse) DecodeFromPtr(p capnp.Ptr) ReparseResponse {
	return ReparseResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ReparseResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s ReparseResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ReparseResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ReparseResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s ReparseResponse) Ok() bool {
	return capnp.Struct(s).Bit(0)
}

func (s ReparseResponse) SetOk(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s ReparseResponse) Generation() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s ReparseResponse) SetGeneration(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s ReparseResponse) Stats() (ParseStats, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ParseStats(p.Struct()), err
}

func (s ReparseResponse) HasStats() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ReparseResponse) SetStats(v ParseStats) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewStats sets the stats field to a newly
// allocated ParseStats struct, preferring placement in s's segment.
func (s ReparseResponse) NewStats() (ParseStats, error) {
	ss, err := NewParseStats(capnp.Struct(s).Segment())
	if err != nil {
		return ParseStats{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// ReparseResponse_List is a list of ReparseResponse.
type ReparseResponse_List = capnp.StructList[ReparseResponse]

// NewReparseResponse creates a new list of ReparseResponse.
func NewReparseResponse_List(s *capnp.Segment, sz int32) (ReparseResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1}, sz)
	return capnp.StructList[ReparseResponse](l), err
}

// ReparseResponse_Future is a wrapper for a ReparseResponse promised by a client call.
type ReparseResponse_Future struct{ *capnp.Future }

func (f ReparseResponse_Future) Struct() (ReparseResponse, error) {
	p, err := f.Future.Ptr()
	return ReparseResponse(p.Struct()), err
}

func (p ReparseResponse_Future) Stats() ParseStats_Future {
	return ParseStats_Future{Future: p.Future.Field(0, nil)}
}

type SnapshotResponse capnp.Struct

// SnapshotResponse_TypeID is the unique identifier for the type SnapshotResponse.
const SnapshotResponse_TypeID = 0xde9a94124a6f6210

func NewSnapshotResponse(s *capnp.Segment) (SnapshotResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return SnapshotResponse(st), err
}

func NewRootSnapshotResponse(s *capnp.Segment) (SnapshotResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return SnapshotResponse(st), err
}

func ReadRootSnapshotResponse(msg *capnp.Message) (SnapshotResponse, error) {
	root, err := msg.Root()
	return SnapshotResponse(root.Struct()), err
}

func (s SnapshotResponse) String() string {
	str, _ := text.Marshal(0xde9a94124a6f6210, capnp.Struct(s))
	return str
}

func (s SnapshotResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SnapshotResponse) DecodeFromPtr(p capnp.Ptr) SnapshotResponse {
	return SnapshotResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SnapshotResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s SnapshotResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SnapshotResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SnapshotResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s SnapshotResponse) Ok() bool {
	return capnp.Struct(s).Bit(0)
}

func (s SnapshotResponse) SetOk(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s SnapshotResponse) Generation() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s SnapshotResponse) SetGeneration(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

// SnapshotResponse_List is a list of SnapshotResponse.
type SnapshotResponse_List = capnp.StructList[SnapshotResponse]

// NewSnapshotResponse creates a new list of SnapshotResponse.
func NewSnapshotResponse_List(s *capnp.Segment, sz int32) (SnapshotResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[SnapshotResponse](l), err
}

// SnapshotResponse_Future is a wrapper for a SnapshotResponse promised by a client call.
type SnapshotResponse_Future struct{ *capnp.Future }

func (f SnapshotResponse_Future) Struct() (SnapshotResponse, error) {
	p, err := f.Future.Ptr()
	return SnapshotResponse(p.Struct()), err
}

type EnrichRequest capnp.Struct

// EnrichRequest_TypeID is the unique identifier for the type EnrichRequest.
const EnrichRequest_TypeID = 0xd8d970c4a80c8bc7

func NewEnrichRequest(s *capnp.Segment) (EnrichRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return EnrichRequest(st), err
}

func NewRootEnrichRequest(s *capnp.Segment) (EnrichRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return EnrichRequest(st), err
}

func ReadRootEnrichRequest(msg *capnp.Message) (EnrichRequest, error) {
	root, err := msg.Root()
	return EnrichRequest(root.Struct()), err
}

func (s EnrichRequest) String() string {
	str, _ := text.Marshal(0xd8d970c4a80c8bc7, capnp.Struct(s))
	return str
}

func (s EnrichRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EnrichRequest) DecodeFromPtr(p capnp.Ptr) EnrichRequest {
	return EnrichRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EnrichRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s EnrichRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EnrichRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EnrichRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s EnrichRequest) Pass() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s EnrichRequest) HasPass() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EnrichRequest) PassBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s EnrichRequest) SetPass(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s EnrichRequest) Files() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.TextList(p.List()), err
}

func (s EnrichRequest) HasFiles() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s EnrichRequest) SetFiles(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewFiles sets the files field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s EnrichRequest) NewFiles(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}

// EnrichRequest_List is a list of EnrichRequest.
type EnrichRequest_List = capnp.StructList[EnrichRequest]

// NewEnrichRequest creates a new list of EnrichRequest.
func NewEnrichRequest_List(s *capnp.Segment, sz int32) (EnrichRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[EnrichRequest](l), err
}

// EnrichRequest_Future is a wrapper for a EnrichRequest promised by a client call.
type EnrichRequest_Future struct{ *capnp.Future }

func (f EnrichRequest_Future) Struct() (EnrichRequest, error) {
	p, err := f.Future.Ptr()
	return EnrichRequest(p.Struct()), err
}

type EnrichResponse capnp.Struct

// EnrichResponse_TypeID is the unique identifier for the type EnrichResponse.
const EnrichResponse_TypeID = 0xb0c273d2f54f6129

func NewEnrichResponse(s *capnp.Segment) (EnrichResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return EnrichResponse(st), err
}

func NewRootEnrichResponse(s *capnp.Segment) (EnrichResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return EnrichResponse(st), err
}

func ReadRootEnrichResponse(msg *capnp.Message) (EnrichResponse, error) {
	root, err := msg.Root()
	return EnrichResponse(root.Struct()), err
}

func (s EnrichResponse) String() string {
	str, _ := text.Marshal(0xb0c273d2f54f6129, capnp.Struct(s))
	return str
}

func (s EnrichResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EnrichResponse) DecodeFromPtr(p capnp.Ptr) EnrichResponse {
	return EnrichResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EnrichResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s EnrichResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EnrichResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EnrichResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s EnrichResponse) Ok() bool {
	return capnp.Struct(s).Bit(0)
}

func (s EnrichResponse) SetOk(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s EnrichResponse) Generation() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s EnrichResponse) SetGeneration(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s EnrichResponse) Passes() (EnrichmentStats_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return EnrichmentStats_List(p.List()), err
}

func (s EnrichResponse) HasPasses() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EnrichResponse) SetPasses(v EnrichmentStats_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewPasses sets the passes field to a newly
// allocated EnrichmentStats_List, preferring placement in s's segment.
func (s EnrichResponse) NewPasses(n int32) (EnrichmentStats_List, error) {
	l, err := NewEnrichmentStats_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return EnrichmentStats_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// EnrichResponse_List is a list of EnrichResponse.
type EnrichResponse_List = capnp.StructList[EnrichResponse]

// NewEnrichResponse creates a new list of EnrichResponse.
func NewEnrichResponse_List(s *capnp.Segment, sz int32) (EnrichResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1}, sz)
	return capnp.StructList[EnrichResponse](l), err
}

// EnrichResponse_Future is a wrapper for a EnrichResponse promised by a client call.
type EnrichResponse_Future struct{ *capnp.Future }

func (f EnrichResponse_Future) Struct() (EnrichResponse, error) {
	p, err := f.Future.Ptr()
	return EnrichResponse(p.Struct()), err
}

type LoadRequest capnp.Struct

// LoadRequest_TypeID is the unique identifier for the type LoadRequest.
const LoadRequest_TypeID = 0x87f896ecb2b01221

func NewLoadRequest(s *capnp.Segment) (LoadRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return LoadRequest(st), err
}

func NewRootLoadRequest(s *capnp.Segment) (LoadRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return LoadRequest(st), err
}

func ReadRootLoadRequest(msg *capnp.Message) (LoadRequest, error) {
	root, err := msg.Root()
	return LoadRequest(root.Struct()), err
}

func (s LoadRequest) String() string {
	str, _ := text.Marshal(0x87f896ecb2b01221, capnp.Struct(s))
	return str
}

func (s LoadRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (LoadRequest) DecodeFromPtr(p capnp.Ptr) LoadRequest {
	return LoadRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s LoadRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s LoadRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s LoadRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s LoadRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s LoadRequest) Db() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s LoadRequest) HasDb() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s LoadRequest) SetDb(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// LoadRequest_List is a list of LoadRequest.
type LoadRequest_List = capnp.StructList[LoadRequest]

// NewLoadRequest creates a new list of LoadRequest.
func NewLoadRequest_List(s *capnp.Segment, sz int32) (LoadRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[LoadRequest](l), err
}

// LoadRequest_Future is a wrapper for a LoadRequest promised by a client call.
type LoadRequest_Future struct{ *capnp.Future }

func (f LoadRequest_Future) Struct() (LoadRequest, error) {
	p, err := f.Future.Ptr()
	return LoadRequest(p.Struct()), err
}

type LoadResponse capnp.Struct

// LoadResponse_TypeID is the unique identifier for the type LoadResponse.
const LoadResponse_TypeID = 0xc30b53f2cee7e736

func NewLoadResponse(s *capnp.Segment) (LoadResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return LoadResponse(st), err
}

func NewRootLoadResponse(s *capnp.Segment) (LoadResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return LoadResponse(st), err
}

func ReadRootLoadResponse(msg *capnp.Message) (LoadResponse, error) {
	root, err := msg.Root()
	return LoadResponse(root.Struct()), err
}

func (s LoadResponse) String() string {
	str, _ := text.Marshal(0xc30b53f2cee7e736, capnp.Struct(s))
	return str
}

func (s LoadResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (LoadResponse) DecodeFromPtr(p capnp.Ptr) LoadResponse {
	return LoadResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s LoadResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s LoadResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s LoadResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s LoadResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s LoadResponse) Ok() bool {
	return capnp.Struct(s).Bit(0)
}

func (s LoadResponse) SetOk(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s LoadResponse) Generation() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s LoadResponse) SetGeneration(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

// LoadResponse_List is a list of LoadResponse.
type LoadResponse_List = capnp.StructList[LoadResponse]

// NewLoadResponse creates a new list of LoadResponse.
func NewLoadResponse_List(s *capnp.Segment, sz int32) (LoadResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[LoadResponse](l), err
}

// LoadResponse_Future is a wrapper for a LoadResponse promised by a client call.
type LoadResponse_Future struct{ *capnp.Future }

func (f LoadResponse_Future) Struct() (LoadResponse, error) {
	p, err := f.Future.Ptr()
	return LoadResponse(p.Struct()), err
}

type QueryRequest capnp.Struct

// QueryRequest_TypeID is the unique identifier for the type QueryRequest.
const QueryRequest_TypeID = 0xc0fb833f6a272dee

func NewQueryRequest(s *capnp.Segment) (QueryRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return QueryRequest(st), err
}

func NewRootQueryRequest(s *capnp.Segment) (QueryRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return QueryRequest(st), err
}

func ReadRootQueryRequest(msg *capnp.Message) (QueryRequest, error) {
	root, err := msg.Root()
	return QueryRequest(root.Struct()), err
}

func (s QueryRequest) String() string {
	str, _ := text.Marshal(0xc0fb833f6a272dee, capnp.Struct(s))
	return str
}

func (s QueryRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (QueryRequest) DecodeFromPtr(p capnp.Ptr) QueryRequest {
	return QueryRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s QueryRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s QueryRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s QueryRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s QueryRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s QueryRequest) Sql() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s QueryRequest) HasSql() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s QueryRequest) SqlBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s QueryRequest) SetSql(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// QueryRequest_List is a list of QueryRequest.
type QueryRequest_List = capnp.StructList[QueryRequest]

// NewQueryRequest creates a new list of QueryRequest.
func NewQueryRequest_List(s *capnp.Segment, sz int32) (QueryRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[QueryRequest](l), err
}

// QueryRequest_Future is a wrapper for a QueryRequest promised by a client call.
type QueryRequest_Future struct{ *capnp.Future }

func (f QueryRequest_Future) Struct() (QueryRequest, error) {
	p, err := f.Future.Ptr()
	return QueryRequest(p.Struct()), err
}

type QueryResponse capnp.Struct

// QueryResponse_TypeID is the unique identifier for the type QueryResponse.
const QueryResponse_TypeID = 0xdf288d6f06549657

func NewQueryResponse(s *capnp.Segment) (QueryResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return QueryResponse(st), err
}

func NewRootQueryResponse(s *capnp.Segment) (QueryResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return QueryResponse(st), err
}

func ReadRootQueryResponse(msg *capnp.Message) (QueryResponse, error) {
	root, err := msg.Root()
	return QueryResponse(root.Struct()), err
}

func (s QueryResponse) String() string {
	str, _ := text.Marshal(0xdf288d6f06549657, capnp.Struct(s))
	return str
}

func (s QueryResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (QueryResponse) DecodeFromPtr(p capnp.Ptr) QueryResponse {
	return QueryResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s QueryResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s QueryResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s QueryResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s QueryResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s QueryResponse) Ok() bool {
	return capnp.Struct(s).Bit(0)
}

func (s QueryResponse) SetOk(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s QueryResponse) Columns() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.TextList(p.List()), err
}

func (s QueryResponse) HasColumns() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s QueryResponse) SetColumns(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewColumns sets the columns field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s QueryResponse) NewColumns(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

func (s QueryResponse) Rows() (QueryRow_List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return QueryRow_List(p.List()), err
}

func (s QueryResponse) HasRows() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s QueryResponse) SetRows(v QueryRow_List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewRows sets the rows field to a newly
// allocated QueryRow_List, preferring placement in s's segment.
func (s QueryResponse) NewRows(n int32) (QueryRow_List, error) {
	l, err := NewQueryRow_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return QueryRow_List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}

// QueryResponse_List is a list of QueryResponse.
type QueryResponse_List = capnp.StructList[QueryResponse]

// NewQueryResponse creates a new list of QueryResponse.
func NewQueryResponse_List(s *capnp.Segment, sz int32) (QueryResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[QueryResponse](l), err
}

// QueryResponse_Future is a wrapper for a QueryResponse promised by a client call.
type QueryResponse_Future struct{ *capnp.Future }

func (f QueryResponse_Future) Struct() (QueryResponse, error) {
	p, err := f.Future.Ptr()
	return QueryResponse(p.Struct()), err
}

type ListChildrenRequest capnp.Struct

// ListChildrenRequest_TypeID is the unique identifier for the type ListChildrenRequest.
const ListChildrenRequest_TypeID = 0x9244609d69f97582

func NewListChildrenRequest(s *capnp.Segment) (ListChildrenRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ListChildrenRequest(st), err
}

func NewRootListChildrenRequest(s *capnp.Segment) (ListChildrenRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ListChildrenRequest(st), err
}

func ReadRootListChildrenRequest(msg *capnp.Message) (ListChildrenRequest, error) {
	root, err := msg.Root()
	return ListChildrenRequest(root.Struct()), err
}

func (s ListChildrenRequest) String() string {
	str, _ := text.Marshal(0x9244609d69f97582, capnp.Struct(s))
	return str
}

func (s ListChildrenRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ListChildrenRequest) DecodeFromPtr(p capnp.Ptr) ListChildrenRequest {
	return ListChildrenRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ListChildrenRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s ListChildrenRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ListChildrenRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ListChildrenRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s ListChildrenRequest) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ListChildrenRequest) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ListChildrenRequest) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ListChildrenRequest) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// ListChildrenRequest_List is a list of ListChildrenRequest.
type ListChildrenRequest_List = capnp.StructList[ListChildrenRequest]

// NewListChildrenRequest creates a new list of ListChildrenRequest.
func NewListChildrenRequest_List(s *capnp.Segment, sz int32) (ListChildrenRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[ListChildrenRequest](l), err
}

// ListChildrenRequest_Future is a wrapper for a ListChildrenRequest promised by a client call.
type ListChildrenRequest_Future struct{ *capnp.Future }

func (f ListChildrenRequest_Future) Struct() (ListChildrenRequest, error) {
	p, err := f.Future.Ptr()
	return ListChildrenRequest(p.Struct()), err
}

type ListChildrenResponse capnp.Struct

// ListChildrenResponse_TypeID is the unique identifier for the type ListChildrenResponse.
const ListChildrenResponse_TypeID = 0x8c804df75f74b5e0

func NewListChildrenResponse(s *capnp.Segment) (ListChildrenResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return ListChildrenResponse(st), err
}

func NewRootListChildrenResponse(s *capnp.Segment) (ListChildrenResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return ListChildrenResponse(st), err
}

func ReadRootListChildrenResponse(msg *capnp.Message) (ListChildrenResponse, error) {
	root, err := msg.Root()
	return ListChildrenResponse(root.Struct()), err
}

func (s ListChildrenResponse) String() string {
	str, _ := text.Marshal(0x8c804df75f74b5e0, capnp.Struct(s))
	return str
}

func (s ListChildrenResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ListChildrenResponse) DecodeFromPtr(p capnp.Ptr) ListChildrenResponse {
	return ListChildrenResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ListChildrenResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s ListChildrenResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ListChildrenResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ListChildrenResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s ListChildrenResponse) Ok() bool {
	return capnp.Struct(s).Bit(0)
}

func (s ListChildrenResponse) SetOk(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s ListChildrenResponse) Children() (Node_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Node_List(p.List()), err
}

func (s ListChildrenResponse) HasChildren() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ListChildrenResponse) SetChildren(v Node_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewChildren sets the children field to a newly
// allocated Node_List, preferring placement in s's segment.
func (s ListChildrenResponse) NewChildren(n int32) (Node_List, error) {
	l, err := NewNode_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Node_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// ListChildrenResponse_List is a list of ListChildrenResponse.
type ListChildrenResponse_List = capnp.StructList[ListChildrenResponse]

// NewListChildrenResponse creates a new list of ListChildrenResponse.
func NewListChildrenResponse_List(s *capnp.Segment, sz int32) (ListChildrenResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[ListChildrenResponse](l), err
}

// ListChildrenResponse_Future is a wrapper for a ListChildrenResponse promised by a client call.
type ListChildrenResponse_Future struct{ *capnp.Future }

func (f ListChildrenResponse_Future) Struct() (ListChildrenResponse, error) {
	p, err := f.Future.Ptr()
	return ListChildrenResponse(p.Struct()), err
}

type ReadContentRequest capnp.Struct

// ReadContentRequest_TypeID is the unique identifier for the type ReadContentRequest.
const ReadContentRequest_TypeID = 0xc0c01ef080ad34b9

func NewReadContentRequest(s *capnp.Segment) (ReadContentRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ReadContentRequest(st), err
}

func NewRootReadContentRequest(s *capnp.Segment) (ReadContentRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ReadContentRequest(st), err
}

func ReadRootReadContentRequest(msg *capnp.Message) (ReadContentRequest, error) {
	root, err := msg.Root()
	return ReadContentRequest(root.Struct()), err
}

func (s ReadContentRequest) String() string {
	str, _ := text.Marshal(0xc0c01ef080ad34b9, capnp.Struct(s))
	return str
}

func (s ReadContentRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ReadContentRequest) DecodeFromPtr(p capnp.Ptr) ReadContentRequest {
	return ReadContentRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ReadContentRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s ReadContentRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ReadContentRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ReadContentRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s ReadContentRequest) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ReadContentRequest) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ReadContentRequest) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ReadContentRequest) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// ReadContentRequest_List is a list of ReadContentRequest.
type ReadContentRequest_List = capnp.StructList[ReadContentRequest]

// NewReadContentRequest creates a new list of ReadContentRequest.
func NewReadContentRequest_List(s *capnp.Segment, sz int32) (ReadContentRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[ReadContentRequest](l), err
}

// ReadContentRequest_Future is a wrapper for a ReadContentRequest promised by a client call.
type ReadContentRequest_Future struct{ *capnp.Future }

func (f ReadContentRequest_Future) Struct() (ReadContentRequest, error) {
	p, err := f.Future.Ptr()
	return ReadContentRequest(p.Struct()), err
}

type ReadContentResponse capnp.Struct

// ReadContentResponse_TypeID is the unique identifier for the type ReadContentResponse.
const ReadContentResponse_TypeID = 0xfd6fe1ba61de2afe

func NewReadContentResponse(s *capnp.Segment) (ReadContentResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return ReadContentResponse(st), err
}

func NewRootReadContentResponse(s *capnp.Segment) (ReadContentResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return ReadContentResponse(st), err
}

func ReadRootReadContentResponse(msg *capnp.Message) (ReadContentResponse, error) {
	root, err := msg.Root()
	return ReadContentResponse(root.Struct()), err
}

func (s ReadContentResponse) String() string {
	str, _ := text.Marshal(0xfd6fe1ba61de2afe, capnp.Struct(s))
	return str
}

func (s ReadContentResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ReadContentResponse) DecodeFromPtr(p capnp.Ptr) ReadContentResponse {
	return ReadContentResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ReadContentResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s ReadContentResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ReadContentResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ReadContentResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s ReadContentResponse) Ok() bool {
	return capnp.Struct(s).Bit(0)
}

func (s ReadContentResponse) SetOk(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s ReadContentResponse) Content() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ReadContentResponse) HasContent() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ReadContentResponse) ContentBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ReadContentResponse) SetContent(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ReadContentResponse) Error() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ReadContentResponse) HasError() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ReadContentResponse) ErrorBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ReadContentResponse) SetError(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// ReadContentResponse_List is a list of ReadContentResponse.
type ReadContentResponse_List = capnp.StructList[ReadContentResponse]

// NewReadContentResponse creates a new list of ReadContentResponse.
func NewReadContentResponse_List(s *capnp.Segment, sz int32) (ReadContentResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[ReadContentResponse](l), err
}

// ReadContentResponse_Future is a wrapper for a ReadContentResponse promised by a client call.
type ReadContentResponse_Future struct{ *capnp.Future }

func (f ReadContentResponse_Future) Struct() (ReadContentResponse, error) {
	p, err := f.Future.Ptr()
	return ReadContentResponse(p.Struct()), err
}

type FindCallersRequest capnp.Struct

// FindCallersRequest_TypeID is the unique identifier for the type FindCallersRequest.
const FindCallersRequest_TypeID = 0xdc70b8674db6e7ec

func NewFindCallersRequest(s *capnp.Segment) (FindCallersRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return FindCallersRequest(st), err
}

func NewRootFindCallersRequest(s *capnp.Segment) (FindCallersRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return FindCallersRequest(st), err
}

func ReadRootFindCallersRequest(msg *capnp.Message) (FindCallersRequest, error) {
	root, err := msg.Root()
	return FindCallersRequest(root.Struct()), err
}

func (s FindCallersRequest) String() string {
	str, _ := text.Marshal(0xdc70b8674db6e7ec, capnp.Struct(s))
	return str
}

func (s FindCallersRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (FindCallersRequest) DecodeFromPtr(p capnp.Ptr) FindCallersRequest {
	return FindCallersRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s FindCallersRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s FindCallersRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s FindCallersRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s FindCallersRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s FindCallersRequest) Token() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s FindCallersRequest) HasToken() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s FindCallersRequest) TokenBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s FindCallersRequest) SetToken(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// FindCallersRequest_List is a list of FindCallersRequest.
type FindCallersRequest_List = capnp.StructList[FindCallersRequest]

// NewFindCallersRequest creates a new list of FindCallersRequest.
func NewFindCallersRequest_List(s *capnp.Segment, sz int32) (FindCallersRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[FindCallersRequest](l), err
}

// FindCallersRequest_Future is a wrapper for a FindCallersRequest promised by a client call.
type FindCallersRequest_Future struct{ *capnp.Future }

func (f FindCallersRequest_Future) Struct() (FindCallersRequest, error) {
	p, err := f.Future.Ptr()
	return FindCallersRequest(p.Struct()), err
}

type FindCallersResponse capnp.Struct

// FindCallersResponse_TypeID is the unique identifier for the type FindCallersResponse.
const FindCallersResponse_TypeID = 0xd0ca99cae34491f1

func NewFindCallersResponse(s *capnp.Segment) (FindCallersResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return FindCallersResponse(st), err
}

func NewRootFindCallersResponse(s *capnp.Segment) (FindCallersResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return FindCallersResponse(st), err
}

func ReadRootFindCallersResponse(msg *capnp.Message) (FindCallersResponse, error) {
	root, err := msg.Root()
	return FindCallersResponse(root.Struct()), err
}

func (s FindCallersResponse) String() string {
	str, _ := text.Marshal(0xd0ca99cae34491f1, capnp.Struct(s))
	return str
}

func (s FindCallersResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (FindCallersResponse) DecodeFromPtr(p capnp.Ptr) FindCallersResponse {
	return FindCallersResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s FindCallersResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s FindCallersResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s FindCallersResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s FindCallersResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s FindCallersResponse) Ok() bool {
	return capnp.Struct(s).Bit(0)
}

func (s FindCallersResponse) SetOk(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s FindCallersResponse) Callers() (Ref_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Ref_List(p.List()), err
}

func (s FindCallersResponse) HasCallers() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s FindCallersResponse) SetCallers(v Ref_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewCallers sets the callers field to a newly
// allocated Ref_List, preferring placement in s's segment.
func (s FindCallersResponse) NewCallers(n int32) (Ref_List, error) {
	l, err := NewRef_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Ref_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// FindCallersResponse_List is a list of FindCallersResponse.
type FindCallersResponse_List = capnp.StructList[FindCallersResponse]

// NewFindCallersResponse creates a new list of FindCallersResponse.
func NewFindCallersResponse_List(s *capnp.Segment, sz int32) (FindCallersResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[FindCallersResponse](l), err
}

// FindCallersResponse_Future is a wrapper for a FindCallersResponse promised by a client call.
type FindCallersResponse_Future struct{ *capnp.Future }

func (f FindCallersResponse_Future) Struct() (FindCallersResponse, error) {
	p, err := f.Future.Ptr()
	return FindCallersResponse(p.Struct()), err
}

type FindDefsRequest capnp.Struct

// FindDefsRequest_TypeID is the unique identifier for the type FindDefsRequest.
const FindDefsRequest_TypeID = 0xdc1a45f85fcd3678

func NewFindDefsRequest(s *capnp.Segment) (FindDefsRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return FindDefsRequest(st), err
}

func NewRootFindDefsRequest(s *capnp.Segment) (FindDefsRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return FindDefsRequest(st), err
}

func ReadRootFindDefsRequest(msg *capnp.Message) (FindDefsRequest, error) {
	root, err := msg.Root()
	return FindDefsRequest(root.Struct()), err
}

func (s FindDefsRequest) String() string {
	str, _ := text.Marshal(0xdc1a45f85fcd3678, capnp.Struct(s))
	return str
}

func (s FindDefsRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (FindDefsRequest) DecodeFromPtr(p capnp.Ptr) FindDefsRequest {
	return FindDefsRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s FindDefsRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s FindDefsRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s FindDefsRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s FindDefsRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s FindDefsRequest) Token() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s FindDefsRequest) HasToken() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s FindDefsRequest) TokenBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s FindDefsRequest) SetToken(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// FindDefsRequest_List is a list of FindDefsRequest.
type FindDefsRequest_List = capnp.StructList[FindDefsRequest]

// NewFindDefsRequest creates a new list of FindDefsRequest.
func NewFindDefsRequest_List(s *capnp.Segment, sz int32) (FindDefsRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[FindDefsRequest](l), err
}

// FindDefsRequest_Future is a wrapper for a FindDefsRequest promised by a client call.
type FindDefsRequest_Future struct{ *capnp.Future }

func (f FindDefsRequest_Future) Struct() (FindDefsRequest, error) {
	p, err := f.Future.Ptr()
	return FindDefsRequest(p.Struct()), err
}

type FindDefsResponse capnp.Struct

// FindDefsResponse_TypeID is the unique identifier for the type FindDefsResponse.
const FindDefsResponse_TypeID = 0x9d29d8c12109eb80

func NewFindDefsResponse(s *capnp.Segment) (FindDefsResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return FindDefsResponse(st), err
}

func NewRootFindDefsResponse(s *capnp.Segment) (FindDefsResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return FindDefsResponse(st), err
}

func ReadRootFindDefsResponse(msg *capnp.Message) (FindDefsResponse, error) {
	root, err := msg.Root()
	return FindDefsResponse(root.Struct()), err
}

func (s FindDefsResponse) String() string {
	str, _ := text.Marshal(0x9d29d8c12109eb80, capnp.Struct(s))
	return str
}

func (s FindDefsResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (FindDefsResponse) DecodeFromPtr(p capnp.Ptr) FindDefsResponse {
	return FindDefsResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s FindDefsResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s FindDefsResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s FindDefsResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s FindDefsResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s FindDefsResponse) Ok() bool {
	return capnp.Struct(s).Bit(0)
}

func (s FindDefsResponse) SetOk(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s FindDefsResponse) Defs() (Ref_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Ref_List(p.List()), err
}

func (s FindDefsResponse) HasDefs() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s FindDefsResponse) SetDefs(v Ref_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewDefs sets the defs field to a newly
// allocated Ref_List, preferring placement in s's segment.
func (s FindDefsResponse) NewDefs(n int32) (Ref_List, error) {
	l, err := NewRef_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Ref_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// FindDefsResponse_List is a list of FindDefsResponse.
type FindDefsResponse_List = capnp.StructList[FindDefsResponse]

// NewFindDefsResponse creates a new list of FindDefsResponse.
func NewFindDefsResponse_List(s *capnp.Segment, sz int32) (FindDefsResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[FindDefsResponse](l), err
}

// FindDefsResponse_Future is a wrapper for a FindDefsResponse promised by a client call.
type FindDefsResponse_Future struct{ *capnp.Future }

func (f FindDefsResponse_Future) Struct() (FindDefsResponse, error) {
	p, err := f.Future.Ptr()
	return FindDefsResponse(p.Struct()), err
}

type GetNodeRequest capnp.Struct

// GetNodeRequest_TypeID is the unique identifier for the type GetNodeRequest.
const GetNodeRequest_TypeID = 0xc93edb48651dd7ca

func NewGetNodeRequest(s *capnp.Segment) (GetNodeRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return GetNodeRequest(st), err
}

func NewRootGetNodeRequest(s *capnp.Segment) (GetNodeRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return GetNodeRequest(st), err
}

func ReadRootGetNodeRequest(msg *capnp.Message) (GetNodeRequest, error) {
	root, err := msg.Root()
	return GetNodeRequest(root.Struct()), err
}

func (s GetNodeRequest) String() string {
	str, _ := text.Marshal(0xc93edb48651dd7ca, capnp.Struct(s))
	return str
}

func (s GetNodeRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GetNodeRequest) DecodeFromPtr(p capnp.Ptr) GetNodeRequest {
	return GetNodeRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GetNodeRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s GetNodeRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GetNodeRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GetNodeRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s GetNodeRequest) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s GetNodeRequest) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s GetNodeRequest) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s GetNodeRequest) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// GetNodeRequest_List is a list of GetNodeRequest.
type GetNodeRequest_List = capnp.StructList[GetNodeRequest]

// NewGetNodeRequest creates a new list of GetNodeRequest.
func NewGetNodeRequest_List(s *capnp.Segment, sz int32) (GetNodeRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[GetNodeRequest](l), err
}

// GetNodeRequest_Future is a wrapper for a GetNodeRequest promised by a client call.
type GetNodeRequest_Future struct{ *capnp.Future }

func (f GetNodeRequest_Future) Struct() (GetNodeRequest, error) {
	p, err := f.Future.Ptr()
	return GetNodeRequest(p.Struct()), err
}

type GetNodeResponse capnp.Struct

// GetNodeResponse_TypeID is the unique identifier for the type GetNodeResponse.
const GetNodeResponse_TypeID = 0xa108b6985b5a5abd

func NewGetNodeResponse(s *capnp.Segment) (GetNodeResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return GetNodeResponse(st), err
}

func NewRootGetNodeResponse(s *capnp.Segment) (GetNodeResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return GetNodeResponse(st), err
}

func ReadRootGetNodeResponse(msg *capnp.Message) (GetNodeResponse, error) {
	root, err := msg.Root()
	return GetNodeResponse(root.Struct()), err
}

func (s GetNodeResponse) String() string {
	str, _ := text.Marshal(0xa108b6985b5a5abd, capnp.Struct(s))
	return str
}

func (s GetNodeResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GetNodeResponse) DecodeFromPtr(p capnp.Ptr) GetNodeResponse {
	return GetNodeResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GetNodeResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s GetNodeResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GetNodeResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GetNodeResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s GetNodeResponse) Ok() bool {
	return capnp.Struct(s).Bit(0)
}

func (s GetNodeResponse) SetOk(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s GetNodeResponse) Node() (Node, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Node(p.Struct()), err
}

func (s GetNodeResponse) HasNode() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s GetNodeResponse) SetNode(v Node) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewNode sets the node field to a newly
// allocated Node struct, preferring placement in s's segment.
func (s GetNodeResponse) NewNode() (Node, error) {
	ss, err := NewNode(capnp.Struct(s).Segment())
	if err != nil {
		return Node{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s GetNodeResponse) Error() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s GetNodeResponse) HasError() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s GetNodeResponse) ErrorBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s GetNodeResponse) SetError(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// GetNodeResponse_List is a list of GetNodeResponse.
type GetNodeResponse_List = capnp.StructList[GetNodeResponse]

// NewGetNodeResponse creates a new list of GetNodeResponse.
func NewGetNodeResponse_List(s *capnp.Segment, sz int32) (GetNodeResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[GetNodeResponse](l), err
}

// GetNodeResponse_Future is a wrapper for a GetNodeResponse promised by a client call.
type GetNodeResponse_Future struct{ *capnp.Future }

func (f GetNodeResponse_Future) Struct() (GetNodeResponse, error) {
	p, err := f.Future.Ptr()
	return GetNodeResponse(p.Struct()), err
}

func (p GetNodeResponse_Future) Node() Node_Future {
	return Node_Future{Future: p.Future.Field(0, nil)}
}

type SubscribeRequest capnp.Struct

// SubscribeRequest_TypeID is the unique identifier for the type SubscribeRequest.
const SubscribeRequest_TypeID = 0x86e4d03ac853e537

func NewSubscribeRequest(s *capnp.Segment) (SubscribeRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return SubscribeRequest(st), err
}

func NewRootSubscribeRequest(s *capnp.Segment) (SubscribeRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return SubscribeRequest(st), err
}

func ReadRootSubscribeRequest(msg *capnp.Message) (SubscribeRequest, error) {
	root, err := msg.Root()
	return SubscribeRequest(root.Struct()), err
}

func (s SubscribeRequest) String() string {
	str, _ := text.Marshal(0x86e4d03ac853e537, capnp.Struct(s))
	return str
}

func (s SubscribeRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SubscribeRequest) DecodeFromPtr(p capnp.Ptr) SubscribeRequest {
	return SubscribeRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SubscribeRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s SubscribeRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SubscribeRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SubscribeRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s SubscribeRequest) Topics() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.TextList(p.List()), err
}

func (s SubscribeRequest) HasTopics() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SubscribeRequest) SetTopics(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewTopics sets the topics field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s SubscribeRequest) NewTopics(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

func (s SubscribeRequest) Identity() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s SubscribeRequest) HasIdentity() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s SubscribeRequest) IdentityBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s SubscribeRequest) SetIdentity(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s SubscribeRequest) Since() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s SubscribeRequest) SetSince(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

// SubscribeRequest_List is a list of SubscribeRequest.
type SubscribeRequest_List = capnp.StructList[SubscribeRequest]

// NewSubscribeRequest creates a new list of SubscribeRequest.
func NewSubscribeRequest_List(s *capnp.Segment, sz int32) (SubscribeRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[SubscribeRequest](l), err
}

// SubscribeRequest_Future is a wrapper for a SubscribeRequest promised by a client call.
type SubscribeRequest_Future struct{ *capnp.Future }

func (f SubscribeRequest_Future) Struct() (SubscribeRequest, error) {
	p, err := f.Future.Ptr()
	return SubscribeRequest(p.Struct()), err
}

type SubscribeResponse capnp.Struct

// SubscribeResponse_TypeID is the unique identifier for the type SubscribeResponse.
const SubscribeResponse_TypeID = 0x9f8f61d321b718a1

func NewSubscribeResponse(s *capnp.Segment) (SubscribeResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0})
	return SubscribeResponse(st), err
}

func NewRootSubscribeResponse(s *capnp.Segment) (SubscribeResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0})
	return SubscribeResponse(st), err
}

func ReadRootSubscribeResponse(msg *capnp.Message) (SubscribeResponse, error) {
	root, err := msg.Root()
	return SubscribeResponse(root.Struct()), err
}

func (s SubscribeResponse) String() string {
	str, _ := text.Marshal(0x9f8f61d321b718a1, capnp.Struct(s))
	return str
}

func (s SubscribeResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SubscribeResponse) DecodeFromPtr(p capnp.Ptr) SubscribeResponse {
	return SubscribeResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SubscribeResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s SubscribeResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SubscribeResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SubscribeResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s SubscribeResponse) Ok() bool {
	return capnp.Struct(s).Bit(0)
}

func (s SubscribeResponse) SetOk(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s SubscribeResponse) HeadSeq() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s SubscribeResponse) SetHeadSeq(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s SubscribeResponse) ReplayCount() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s SubscribeResponse) SetReplayCount(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s SubscribeResponse) ReplayGap() bool {
	return capnp.Struct(s).Bit(1)
}

func (s SubscribeResponse) SetReplayGap(v bool) {
	capnp.Struct(s).SetBit(1, v)
}

// SubscribeResponse_List is a list of SubscribeResponse.
type SubscribeResponse_List = capnp.StructList[SubscribeResponse]

// NewSubscribeResponse creates a new list of SubscribeResponse.
func NewSubscribeResponse_List(s *capnp.Segment, sz int32) (SubscribeResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0}, sz)
	return capnp.StructList[SubscribeResponse](l), err
}

// SubscribeResponse_Future is a wrapper for a SubscribeResponse promised by a client call.
type SubscribeResponse_Future struct{ *capnp.Future }

func (f SubscribeResponse_Future) Struct() (SubscribeResponse, error) {
	p, err := f.Future.Ptr()
	return SubscribeResponse(p.Struct()), err
}

type ErrorResponse capnp.Struct

// ErrorResponse_TypeID is the unique identifier for the type ErrorResponse.
const ErrorResponse_TypeID = 0xb7dd705c70c8f072

func NewErrorResponse(s *capnp.Segment) (ErrorResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ErrorResponse(st), err
}

func NewRootErrorResponse(s *capnp.Segment) (ErrorResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ErrorResponse(st), err
}

func ReadRootErrorResponse(msg *capnp.Message) (ErrorResponse, error) {
	root, err := msg.Root()
	return ErrorResponse(root.Struct()), err
}

func (s ErrorResponse) String() string {
	str, _ := text.Marshal(0xb7dd705c70c8f072, capnp.Struct(s))
	return str
}

func (s ErrorResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ErrorResponse) DecodeFromPtr(p capnp.Ptr) ErrorResponse {
	return ErrorResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ErrorResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s ErrorResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ErrorResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ErrorResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s ErrorResponse) Error() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ErrorResponse) HasError() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ErrorResponse) ErrorBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ErrorResponse) SetError(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// ErrorResponse_List is a list of ErrorResponse.
type ErrorResponse_List = capnp.StructList[ErrorResponse]

// NewErrorResponse creates a new list of ErrorResponse.
func NewErrorResponse_List(s *capnp.Segment, sz int32) (ErrorResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[ErrorResponse](l), err
}

// ErrorResponse_Future is a wrapper for a ErrorResponse promised by a client call.
type ErrorResponse_Future struct{ *capnp.Future }

func (f ErrorResponse_Future) Struct() (ErrorResponse, error) {
	p, err := f.Future.Ptr()
	return ErrorResponse(p.Struct()), err
}

const schema_a1b2c3d4e5f60001 = "x\xda\xacWql\x14\xc7\xf5\x9e\xb7s\xe7\xf3\xd9>" +
	"\xdf\x9d\xd7?\xfd\x12\xd4\xd6\"J\x14\xb0J\x05vH" +
	"\x8b\xa5\xf4\x02\xd8\x01#L=v\xd4\x10\x97\x08\xd6\xb7" +
	"\x03\xdep\xde=\xef\xee\x05L\x1baRTB\x0aj" +
	"@$*Q\xad\xc6j\xa9@J\x1a@%\x90V\x95" +
	"R\xd2\xaa\xc1\x12\x15\xd0V!$\xa1\xc5-\xb2\xa0\xd0" +
	"R\xda\x84\xb4\x11q\xf5f\xefv\xf7n\xcf\x9c+\xf5" +
	"\xbf\xb9\xd1wo\xbe\xf9\xde\xf7\xde\x9b\x9doU=\x1c" +
	"Z\x10[[K$\xb6=\\5\xf5\xc5\xcb\xbdo\xb7" +
	"\x9d\xf9\xf3\xb7\x08\x8b\x01\xdc\x86\x8f.\xff\xee\xad\xa3c" +
	"a)B\x88\xfcB\xf8\xa6<\x16\xc6\xd5h\xf85\x02" +
	"S\xb7N\x9d\x99\xdc\xf7\xa3gw Tr\xa1!\x04" +
	"tV\xed\x95YU\x84\x90\xd6\xae\xaa\xc7\x80\xc0\xd4\xec" +
	"\x86\xc3G\xaf\xbd\xf8\xf1\x0e\x92\x8cyQA\xc4\x8a\x8c" +
	"\xcb\x87\"\xb8:\x10Ia\xd4O\xa2\xd7>\xfaz\xfb" +
	"sEHq\xfe\xaf\"\x13\xf2Y\x81<\x1d\xd9D`" +
	"\xea\x8f\xc7\xec\xb5\xb7\xbaFv\x15S\xc5\xa0\xads\xab" +
	"\x1b@^T\x8d\xd8\x85\xd5\x88}&\xf7/mt]" +
	"\xfb\xde\xc0\xf9\xad\x07\xaak@>&\xa0G\xaa\x91\xc0" +
	"\xd1\x9d\x1f~&|\xbea4H\xe0l\xf5s\xf2\xbb" +
	"\x02\xf9{\x11t\xe4/\xd1\xd9\xbf8?w4H@" +
	"^\x18\xbd)/\x8e\xe2\xea\xa1(B\xc7\xee:>\xfb" +
	"\xb7\xcaw\xbe\x8fPZ\x80\x0a\xa9\x0eE\xff-\x1f\x13" +
	"\xc8#\xd1I\x02S?\xef\xeb\xfb\xdaw_\xaf\x1e+" +
	"\x93\x80\xdd5W\xe5\xfd5\"\x155\x98\x80\xb9\xcaW" +
	"><g\x9d<\\\x9c\x00q\xfe\xbc\xda\x09yQ\xad" +
	"`R\x8bP\xf3\xc6\xdb\xd95\xd9\x0f\x8e\x07\xf5\xbfT" +
	"{A\xbe.\x90Wj\xf1\xfaw\xa7\x07\x9a\xde[\xf6" +
	"\x83\x13\xc5\xe7S\x04D\xeb^\x92\x93u\xb8\x8a\xd5!" +
	"\xd57\x1exu\xe4\xc6\xe7\xde|3(\xea\xa5:\x09" +
	"\xe4\xeb\x02z\xa5\x0e\xa3\xfeu\xde\xfdO\xa6\xbe\xf9I" +
	"\x10*Gc\xe7\xe4\xff\x8b\xe1*\x19C\xe4\xae\xf7\xff" +
	"\x19[\xf3i\xd7\xc9\"\xa5\x1c\xe8\x82\xd8\x84\xfc\x90\x80" +
	".\x8a\xe1\xf9\x0fNN\xfe\xe6fo\xed[E\xf7\x17" +
	"\xa2\xde]\x7fN\xbe\xaf\x1eW\xb3\xebQ\xfe7\xd6\xed" +
	"\x18\xff\xff[\xf7\x9f*\xa3\xd4\xb6\xfa\xab\xf2n\x01\xdd" +
	"Y\x8fJ\x8d\xbf\xf3Y\xbe\xfc\xbd/\x9f\x0a2\xbd/" +
	">!/\x88\x0bu\xe3\xc8\xf4\xef{\xda\xff4\xbe\x7f" +
	"\xfcL\x19\xffu\xc5k@~B`\x1f\x8f#\x81_" +
	"\x7f\xbb\xee\xe0/\xb3\xef\x9e/\xe3\xea\xf8\x05\xf9\xac@" +
	"\x9e\x16\xc8\xcd\x0f\x9e^\xfbq\xc7\xac\xf7\x83\xe7/J" +
	"\\\x95;\x12\xb8Z\x9c\xc0\xf3\xafM\xbe\xde\xb5\xe1D" +
	"6\x88lU\x12\x12\xc8\x83\x02\xaa\x09\xe8\xc2\xeb\xb3\x9f" +
	"y\xe7\xab\xf3/\x96\x11ug\xe2\xaa\xfc\x82\x80\xeeI" +
	"\xa0\xa8\x89~cE\xc3\xbe\x97.\x06E\xcd%o\xca" +
	"\xdb\x92\xb8z:\x89L\x1f{\xf1\xd1*c\xf7\x9c?" +
	"\x94q\xea\x07\xc9\x0b\xf2\x15\x01\xbd\x9cDQW\x1f\xaf" +
	"\x91\xda~\xacO 4TR\xff\x0d'\xe5\x03\x0d\xc8" +
	"z\xac\xa1\x09[\xc5^\xe9\xc6\xc99\x7f\xfb\xd9?\x82" +
	"\x02\x9c\x92\x8f\xcage!\x95\x8c\xb7\xfa\xb4\xf9\xa2\xf2" +
	"\xd3K\xc6\xed \x81\xd6\xdbr\x0d\xc8\xb1Fa\xb0\xc6" +
	"\xd7\xc8\xbc)U\xe1\x83\x86\xfe\x85\xb4\xa4d\xf5l[" +
	"o\xae\xdfJ\x9bZ?\xef\xe1MC9n\xd9\xdd\x00" +
	"\xac\x8e\x86\x08\x09\x01!\xc9\x8e6B\xd8\xc3\x14\xd8\x1a" +
	"\x09\x92\x00\x8d\x80\x9b\x8f\xaf \x84\xad\xa6\xc0T\x09@" +
	"j\x04\x89\x90\xa4\xd2B\x08[C\x81\x0dH\x90\xb2\x8d" +
	"\xac\x96\xb6\xa0\x9e@7\x05\xa8#\x12.\xa74\x95\xeb" +
	"\xb6f\x0f\x13B\xc4^\x1d\x81&K\xd3\xd3\x1c\xa2D" +
	"\x82(\x01\x97\x1a\x08j\xab\x0c\x158\xd2\xb9\xcb\xa5\xb3" +
	"\x7f\x16!l\x1f\x05\xf6\xb2\x8f\xce(\xd2\xf9\x1e\x05v" +
	"P\x82\xa4\x94\xe7s\xa0\x99\x10\xf62\x05\xf6\x8a\x04@" +
	"\x1b\x81\x12\x92<\x84{?\xa4\xc0\x0eK\x90\x0cA#" +
	"\x84\x08I\xbe\x8a\x9b\x07)\xb0\x9fH\x90\x0c\xd3F\x08" +
	"\x13\x92<\x82\xd7~\x85\x02;!\x01\xd5\xd4\x02\xdd\xa9" +
	"\xacbr\xdd\xeeT}W\x88\xeb\xca w\x7fl\xd4" +
	"t\x15BD\x82\x10\x81\xb8\xa5m\xe1\x10&\x12\x84\x09" +
	"\xa4L\x9e6L/Rq\x16V\x1a\x8a\xda\xc3\x85\xfe" +
	"\x84\xe0\x95C\xee\x95cx\xe5j\x0a\xacQ\x02\xaa\xf6" +
	"C\x8cH\x10\x0b\x04\xe8\xe1Y\xc5\xb48\xc6\x88\xe4\x93" +
	"X\xed\x86\x98\x8b\xb7\xb9\x97\x02\x9b\xefSm\x1e\xde{" +
	"\x0e\x05\xf6\x80\x04)\xcb\xc8\x99i\xef\x16\x19E\xdf\x10" +
	"`J\x1d\xa6\x9ae/\x1d\xd02\xaa\xc9\xf5\x1ene" +
	"\x0d\xddr\x92\xe4;n\x96w\x9c{\x1a\xe6\xe8\xf3\x14" +
	"\xd8r\x09\xa8\xb1\x11\x80H\x80\x16O\xe7C\xa1\xa0y" +
	"\xbb$\xbcqJ@\x18\xe7N\x0c*k\xa6\x05E\x87" +
	"\xbcf\xeb\x9d?VR\xaa\xc0\xfdK\x12\xa4tC\xe5" +
	"\x9d^DG\xb8\"C\x94d\xe6\x11MW\xdb\xf9z" +
	"\xab\x87[M\xa8\xd6L\xc4*\xa4\xa6\xbdH\xac\xb8\xca" +
	"\xd7[\x9eJ\xeet.Q)P\xd7)\xcb=7\xe1" +
	"\x9e\xab\xcc\xf2\xea\xd5\xbd)_B\x08[G\x81e|" +
	"\x95\xa4\xf5\x13\xc2\x06(0[\x82$\x05\xa7\x94\x86z" +
	"\x08aY\x0a\xec\x1bE\x14\xb7\x0epE\xed\xe5Cn" +
	"E\x9b<\x9bQ\x86\x97\x1a$\x92\xd3\xed\x92\xdde\x0a" +
	"\x81\xac\xeb\x84b\xfa\xcb\xb8\xbd\xcaP9:,^ " +
	"\xef\xebJ\xb3\xf2]i\xa5'Z'\x8a\xd6N\x81u" +
	"#wp\xb8waWZN\x81=Z\xac$f\xb1" +
	"\xc4h\x09\x02M\xdc4\x0ds\x9a<v\xe8\xa6\x96\x1e" +
	"\x10\x96\x8f\xdc\x91\x90\xabfg\x9fwx\xa1M24" +
	"\xd8JGv\x7f\x1dl\xe0:7\x15[#\xd4\xd0\x0b" +
	"2\xa5\xb2\x8aeq_\xc6\xdd\xd9U6\xe3\x1dH\xde" +
	")I\xea\xf0\xf3\x15D\x8bW\x10\xd3\xdc\xd2\xa9\x89\x8e" +
	"\xa78\xd5\xed\x12\xab\xdc\xe3Y\xc5uJ\x8b\xdf)y" +
	"\xb55\xbc\x9cJ\x81e\xd1)\x92\xe3\x94\xc1f\xcf>" +
	"\x11\xcb\xb3F\x93\x18\x12\x05\x1a\xa5\x1dHUle\x9a" +
	"\x0e\xd4\xc3\x15u\xa9\xa1\xdb\\\xb7\x0b\xe5\xff\xdfU\xbf" +
	"#\x17\xcbqs\xd8\x09\x00vI\x80{\xbc\x00\x11k" +
	"(3M\x84^[\xb1sV\x91#*\xd5W\x9f'" +
	"P\xc1\x11\x83XI\x19\x0al\xb3O\xb4\x1cn\xda\x14" +
	"\xd8He\x9bL\xe1LR\xba\x15\x9b\xc0\x80\xcbT\xec" +
	"\xf5j[\x08\x04\xa7\xab\x7f\xe4Tl\xe0^\x17\xec\xf3" +
	"\xba`EJ\xd3\x0c\xa7\x8a\xc5|\xe7\xdai\xc9\xd7\xce" +
	"\xea\xca\x0c\x9a,[\xb1-Hx\xef-\xa7\xc4\xa7k" +
	"3\xde\xd8\x9c\xb9\x8f\xa8\xdb\xdf\x97*\x99\x0c7\xad\xbc" +
	"\x9c<0U\xca\xf5\xf8%e{\xfc\xd6\xb4\x13j\xa6" +
	"m\xbe\xd0\x95\x86r\x9c\x06\xc6~s\xb94\xb6x\xe7" +
	"\xc6\xb1\xc1\xb8O\xb1\xf5Z\x86\x07\xdel\xd3\xcd\xb2\xa1" +
	"x.\xa8\x97\xbf\xc9\xd8\xc6F\xae\xcfD\xb2\xb2\x15\\" +
	"9\x92\xff\xfa\x83\\\xb7{\xe3\x98\xf0\x92\x1a\\\xe15" +
	"\xa9\xc2\xfd\xb5-\xbeiVh\\C}\xde4sk" +
	"p\x1877S`\xdb%|\xf8Y\xd6*e\x90\xfb" +
	"\xe7\xbc\x10\xac\xdb4H*\xcd-\x8b\xab\xae\xfb5\x9b" +
	"\x0fZ\x8bU\x95P\xdf\xa6\x9aC\x8f\x1a:\xa1]\xd6" +
	"4u\xd2\xab+Yk\xc0\xb0g\xf0T\xf8_\x94e" +
	"\xbe\x03\xfa\x06F\x85\x09\xbb$?a\xd7\xf9\xa4{\xa2" +
	"9\xff-`\x97\xf8\xd8\xc8\xe4\x06\xf5R?\xc5Mc" +
	"\x93\xcf\xdb\xee\x07NYowc\xd3\xc0&k\x09{" +
	"4\xba\xe4\x9en\xf32\xe3\x0a\xb1\x0d[\xe6\x08\x05\xb6" +
	"\xcb\xf7v\xd9\x89\x94\xb7S`\xcfcb\xf3\x9f\x01\xbb" +
	"\xf1\xef\xcfR`\xfb$\x80\x90\xf3\x15\xb0\xe7IB\xd8" +
	"\xf3\xce\xe7BJt+/s9==\xa0\xe8\x1b8" +
	"\x01wo\xab\xca3\xdc\xf60)1S\xbd\xbc:\x7f" +
	"P\x1f!\xf1;\x15\x15\x14\xd2\xd0d\x0e\xf7\x18\x9bJ" +
	"j\xa0-_\x03\xf7J\x90zJ\xc9\xe4\xa6\x8fSf" +
	".\xfa\x1b\xd1\x0c\xb3:\x83w\xd3\xd6\xb4\x13\xdf\xed\x19" +
	"EO\x89\xff\x04\x00\x00\xff\xffU\xbf\x85\x92"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_a1b2c3d4e5f60001,
		Nodes: []uint64{
			0x86e4d03ac853e537,
			0x8788a694e7d0c9f7,
			0x87f896ecb2b01221,
			0x8a447bf6ec09fbf7,
			0x8c804df75f74b5e0,
			0x9244609d69f97582,
			0x9d12d8051cf589b2,
			0x9d29d8c12109eb80,
			0x9f8f61d321b718a1,
			0xa108b6985b5a5abd,
			0xb0c273d2f54f6129,
			0xb7dd705c70c8f072,
			0xb8a347db1f686319,
			0xc0c01ef080ad34b9,
			0xc0fb833f6a272dee,
			0xc24dfe5c0df4dc8c,
			0xc30b53f2cee7e736,
			0xc927f717ca8760b9,
			0xc93edb48651dd7ca,
			0xd0ca99cae34491f1,
			0xd8d970c4a80c8bc7,
			0xdc1a45f85fcd3678,
			0xdc70b8674db6e7ec,
			0xde3056d78221ed35,
			0xde9a94124a6f6210,
			0xdf288d6f06549657,
			0xe26eae3a020ab758,
			0xf3bbef28c2f00292,
			0xfd6fe1ba61de2afe,
		},
		Compressed: true,
	})
}
