package cmd

import (
	"bytes"
	"context"
	"database/sql"
	"strings"
	"testing"

	"github.com/agentic-research/mache/internal/graph"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// smellParityGraph is the serve-mode backend shape: a graph.Graph that also
// carries a SQL handle and a .db path. MemoryStore supplies the Graph surface;
// the two capabilities the smell engine actually reaches for are delegated to
// the very *dbQuerier the CLI runs on.
//
// Sharing the production querier rather than re-implementing it is what makes
// the parity claim tight: with both sides driving identical QueryRefs/DBPath
// behavior, the only remaining difference between the two paths is the
// lazyGraph wrapper — which is exactly the thing under test.
type smellParityGraph struct {
	*graph.MemoryStore
	q *dbQuerier
}

func (s *smellParityGraph) QueryRefs(query string, args ...any) (*sql.Rows, error) {
	return s.q.QueryRefs(query, args...)
}

func (s *smellParityGraph) DBPath() string { return s.q.DBPath() }

// runSmellCLIJSON runs one rule through the find-smells CLI and returns its
// JSON payload. The Encoder's trailing newline is stream framing, not payload,
// so it is trimmed — everything else must match the MCP bytes exactly.
func runSmellCLIJSON(t *testing.T, dbPath, rule string) string {
	t.Helper()
	saved := saveCLIFlags()
	t.Cleanup(saved.restore)
	findSmellsRule = rule
	findSmellsDBPath = dbPath
	findSmellsFormat = "json"
	findSmellsSourceID = ""
	findSmellsTags = ""
	findSmellsBaseline = ""
	findSmellsWriteBaseline = ""
	findSmellsBaselineRoot = ""
	findSmellsLimit = 200

	var buf bytes.Buffer
	findSmellsCmd.SetOut(&buf)
	findSmellsCmd.SetErr(&buf)
	code, err := runFindSmells(findSmellsCmd, nil)
	require.NoError(t, err)
	require.Equal(t, 0, code, "CLI run must succeed: %s", buf.String())
	return strings.TrimRight(buf.String(), "\n")
}

// runSmellMCPJSON runs the same rule through the find_smells MCP handler,
// against a *lazyGraph — the graph a handler actually holds in serve mode,
// not the backend underneath it.
func runSmellMCPJSON(t *testing.T, dbPath, rule string) string {
	t.Helper()
	db, err := sql.Open("sqlite", dbPath)
	require.NoError(t, err)
	t.Cleanup(func() { _ = db.Close() })
	// Same single-connection pinning the CLI applies: the TEMP tables that
	// ensureSmellQueryContext creates are per-connection, so a pool that hands
	// out a second connection loses them non-deterministically.
	db.SetMaxOpenConns(1)

	lg := newTestLazyGraph(&smellParityGraph{
		MemoryStore: graph.NewMemoryStore(),
		q:           &dbQuerier{db: db, path: dbPath},
	}, "")

	res, err := makeFindSmellsHandler(lg)(context.Background(), makeRequest(map[string]any{
		"rule": rule, "limit": float64(200),
	}))
	require.NoError(t, err)
	require.False(t, res.IsError, "MCP run must succeed: %s", resultText(t, res))
	return resultText(t, res)
}

// TestFindSmells_MCPAndCLI_ByteForByteParity is the standing proof that the
// two consumers of the smell engine give the same answer over the same .db.
//
// That property is load-bearing rather than aesthetic: the committed smell
// baseline is generated by the CLI, and the ratchet only means anything to an
// agent calling the MCP tool if both see the same findings. The two had
// already drifted in two independent ways — a capability the MCP path could
// not reach, and an envelope each path built for itself.
func TestFindSmells_MCPAndCLI_ByteForByteParity(t *testing.T) {
	// A rule with findings: the shared path must agree on content AND shape.
	t.Run("with findings", func(t *testing.T) {
		dbPath := writeSmellCLIFixture(t)

		cliOut := runSmellCLIJSON(t, dbPath, "dead_code")
		mcpOut := runSmellMCPJSON(t, dbPath, "dead_code")

		require.Contains(t, cliOut, "pkg/Dead", "fixture must actually produce a finding, or this proves nothing")
		assert.Equal(t, cliOut, mcpOut, "same rules, same .db — the bytes must match")
	})

	// The discriminating case. A sibling .bindings.capnp record marking
	// pkg/Dead as referenced reaches the rule only through DBPath ->
	// LoadCapnpBindings -> the _capnp_binding_refs arm of v_refs. Before
	// lazyGraph forwarded DBPath, the CLI saw this record and the MCP handler
	// did not, so the two paths disagreed about whether pkg/Dead was dead.
	t.Run("capnp binding is visible to both paths", func(t *testing.T) {
		dbPath := writeSmellCLIFixture(t)
		writeBindingLogForTest(t, dbPath,
			"pkg/Dead", "Dead", "pkg/Caller", "file:///pkg/caller.go")

		cliOut := runSmellCLIJSON(t, dbPath, "dead_code")
		mcpOut := runSmellMCPJSON(t, dbPath, "dead_code")

		assert.Equal(t, cliOut, mcpOut, "the capnp binding log must be reachable from BOTH paths")
		assert.NotContains(t, mcpOut, "pkg/Dead",
			"a capnp binding referencing pkg/Dead must retire the dead_code finding; "+
				"if it still fires, the MCP path is not reading the sibling log")
	})

	// A clean run is where the envelope divergence lived: a nil finding set
	// marshals to `null`, and only the CLI normalized it to `[]`.
	t.Run("clean run emits the same empty shape", func(t *testing.T) {
		dbPath := writeSmellCLIFixture(t)

		cliOut := runSmellCLIJSON(t, dbPath, "duplicate_definitions")
		mcpOut := runSmellMCPJSON(t, dbPath, "duplicate_definitions")

		assert.Equal(t, cliOut, mcpOut)
		assert.Contains(t, cliOut, `"findings": []`,
			`zero findings must serialize as [] on both paths, never null`)
	})
}
