package cmd

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/agentic-research/mache/api"
	_ "modernc.org/sqlite"
)

// materializeVirtuals adds virtual file nodes to the .db so that leyline's
// NFS mount can serve them without mache-specific runtime logic.
//
// Materialized files:
//   - _schema.json  (schema topology as JSON)
//   - PROMPT.txt    (if agentMode)
//   - callers/ dirs (from node_refs cross-references)
func materializeVirtuals(dbPath string, schema *api.Topology, agentMode bool) error {
	db, err := sql.Open("sqlite", dbPath)
	if err != nil {
		return fmt.Errorf("open db: %w", err)
	}
	defer func() { _ = db.Close() }()

	tx, err := db.Begin()
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback() }()

	now := time.Now().UnixNano()

	// 1. _schema.json at root
	schemaJSON, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal schema: %w", err)
	}
	if _, err := tx.Exec(
		`INSERT OR REPLACE INTO nodes (id, parent_id, name, kind, size, mtime, record) VALUES (?, ?, ?, ?, ?, ?, ?)`,
		"_schema.json", "", "_schema.json", 0, len(schemaJSON), now, string(schemaJSON),
	); err != nil {
		return fmt.Errorf("insert _schema.json: %w", err)
	}

	// 2. PROMPT.txt if agent mode
	if agentMode {
		prompt := "# Mache Agent Mode\n\nThis mount was generated by mache for use with AI agents.\nRead source files under the function directories.\n"
		if _, err := tx.Exec(
			`INSERT OR REPLACE INTO nodes (id, parent_id, name, kind, size, mtime, record) VALUES (?, ?, ?, ?, ?, ?, ?)`,
			"PROMPT.txt", "", "PROMPT.txt", 0, len(prompt), now, prompt,
		); err != nil {
			return fmt.Errorf("insert PROMPT.txt: %w", err)
		}
	}

	// 3. Materialize callers
	if err := materializeCallers(tx, now); err != nil {
		return fmt.Errorf("materialize callers: %w", err)
	}

	// 4. Materialize callees
	if err := materializeCallees(tx, now); err != nil {
		return fmt.Errorf("materialize callees: %w", err)
	}

	// 5. Materialize LSP data (hover, diagnostics) if _lsp_* tables exist
	if err := materializeLSP(tx, now); err != nil {
		return fmt.Errorf("materialize lsp: %w", err)
	}

	return tx.Commit()
}

// materializeCallers reads node_refs and creates callers/ directory nodes
// for each function directory that has callers.
//
// For a ref (token="HandleRequest", node_id="functions/ProcessOrder/source"),
// this creates:
//   - functions/HandleRequest/callers       (dir)
//   - functions/HandleRequest/callers/ProcessOrder (file, content = node_id)
func materializeCallers(tx *sql.Tx, now int64) error {
	// Check if node_refs table exists
	var count int
	err := tx.QueryRow(`SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='node_refs'`).Scan(&count)
	if err != nil || count == 0 {
		return nil // no refs table, nothing to do
	}

	// Read all refs: token -> list of calling node IDs
	rows, err := tx.Query(`SELECT token, node_id FROM node_refs`)
	if err != nil {
		return fmt.Errorf("query node_refs: %w", err)
	}
	defer func() { _ = rows.Close() }()

	// Group by token
	callerMap := make(map[string][]string) // token -> []callerNodeID
	for rows.Next() {
		var token, nodeID string
		if err := rows.Scan(&token, &nodeID); err != nil {
			return err
		}
		callerMap[token] = append(callerMap[token], nodeID)
	}
	if err := rows.Err(); err != nil {
		return err
	}

	// For each token, find the matching directory node (via node_defs)
	// and create callers/ entries
	for token, callerNodeIDs := range callerMap {
		// Look up the directory that defines this token
		var dirID string
		err := tx.QueryRow(`SELECT dir_id FROM node_defs WHERE token = ?`, token).Scan(&dirID)
		if err != nil {
			continue // no definition found, skip
		}

		// Create callers/ directory under the defining dir
		callersID := dirID + "/callers"

		// Check if callers/ dir already exists
		var exists int
		_ = tx.QueryRow(`SELECT COUNT(*) FROM nodes WHERE id = ?`, callersID).Scan(&exists)
		if exists == 0 {
			if _, err := tx.Exec(
				`INSERT INTO nodes (id, parent_id, name, kind, size, mtime, record) VALUES (?, ?, ?, ?, ?, ?, ?)`,
				callersID, dirID, "callers", 1, 0, now, nil,
			); err != nil {
				return fmt.Errorf("insert callers dir %s: %w", callersID, err)
			}
		}

		// Create an entry for each caller
		for _, callerNodeID := range callerNodeIDs {
			// Extract the caller's function name from the node_id path
			// e.g. "functions/ProcessOrder/source" -> "ProcessOrder"
			callerName := extractFuncName(callerNodeID)
			if callerName == "" {
				continue
			}

			entryID := callersID + "/" + callerName
			// Check if entry already exists
			var entryExists int
			_ = tx.QueryRow(`SELECT COUNT(*) FROM nodes WHERE id = ?`, entryID).Scan(&entryExists)
			if entryExists > 0 {
				continue
			}

			content := callerNodeID // content points to the calling node
			if _, err := tx.Exec(
				`INSERT INTO nodes (id, parent_id, name, kind, size, mtime, record) VALUES (?, ?, ?, ?, ?, ?, ?)`,
				entryID, callersID, callerName, 0, len(content), now, content,
			); err != nil {
				return fmt.Errorf("insert caller entry %s: %w", entryID, err)
			}
		}
	}

	return nil
}

// materializeCallees reads node_refs and creates callees/ directory nodes
// for each function directory that calls other functions.
// This is the inverse of materializeCallers: callers/ shows "who calls me",
// callees/ shows "who do I call".
//
// For a ref (token="FuncB", node_id="pkg/functions/FuncA"),
// with a def (token="FuncB", dir_id="pkg/functions/FuncB"),
// this creates:
//   - pkg/functions/FuncA/callees       (dir)
//   - pkg/functions/FuncA/callees/FuncB (file, content = dir_id of the callee)
func materializeCallees(tx *sql.Tx, now int64) error {
	// Check if required tables exist
	var count int
	err := tx.QueryRow(`SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='node_refs'`).Scan(&count)
	if err != nil || count == 0 {
		return nil
	}
	err = tx.QueryRow(`SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='node_defs'`).Scan(&count)
	if err != nil || count == 0 {
		return nil
	}

	// Pre-load all defs: token → []dir_id (multiple constructs may define
	// the same token, e.g. Init in different packages).
	defsMap := make(map[string][]string)
	defRows, err := tx.Query(`SELECT token, dir_id FROM node_defs`)
	if err != nil {
		return fmt.Errorf("query node_defs: %w", err)
	}
	for defRows.Next() {
		var token, dirID string
		if err := defRows.Scan(&token, &dirID); err != nil {
			_ = defRows.Close()
			return err
		}
		defsMap[token] = append(defsMap[token], dirID)
	}
	_ = defRows.Close()
	if err := defRows.Err(); err != nil {
		return err
	}

	// Read all refs and resolve callees via the pre-loaded defs map.
	rows, err := tx.Query(`SELECT token, node_id FROM node_refs`)
	if err != nil {
		return fmt.Errorf("query node_refs: %w", err)
	}

	// Group by caller dir: callerDir -> list of (token, callee dir_id)
	type calleeInfo struct {
		token string
		dirID string
	}
	callerCallees := make(map[string][]calleeInfo) // callerDir -> callees

	for rows.Next() {
		var token, nodeID string
		if err := rows.Scan(&token, &nodeID); err != nil {
			_ = rows.Close()
			return err
		}

		// Find the caller's directory (parent of the referencing node)
		callerDir := extractCallerDir(nodeID)
		if callerDir == "" {
			continue
		}

		// Look up in pre-loaded map — emit one edge per definition
		dirIDs, ok := defsMap[token]
		if !ok {
			continue // no definition found
		}
		for _, calleeDirID := range dirIDs {
			callerCallees[callerDir] = append(callerCallees[callerDir], calleeInfo{token: token, dirID: calleeDirID})
		}
	}
	_ = rows.Close()
	if err := rows.Err(); err != nil {
		return err
	}

	// Create callees/ directories and entries
	for callerDir, callees := range callerCallees {
		// Verify caller dir exists in nodes
		var exists int
		_ = tx.QueryRow(`SELECT COUNT(*) FROM nodes WHERE id = ?`, callerDir).Scan(&exists)
		if exists == 0 {
			continue
		}

		calleesID := callerDir + "/callees"

		// Create callees/ directory
		var dirExists int
		_ = tx.QueryRow(`SELECT COUNT(*) FROM nodes WHERE id = ?`, calleesID).Scan(&dirExists)
		if dirExists == 0 {
			if _, err := tx.Exec(
				`INSERT INTO nodes (id, parent_id, name, kind, size, mtime, record) VALUES (?, ?, ?, ?, ?, ?, ?)`,
				calleesID, callerDir, "callees", 1, 0, now, nil,
			); err != nil {
				return fmt.Errorf("insert callees dir %s: %w", calleesID, err)
			}
		}

		// Create entry for each callee
		for _, callee := range callees {
			calleeName := callee.token

			entryID := calleesID + "/" + calleeName
			var entryExists int
			_ = tx.QueryRow(`SELECT COUNT(*) FROM nodes WHERE id = ?`, entryID).Scan(&entryExists)
			if entryExists > 0 {
				continue
			}

			content := callee.dirID
			if _, err := tx.Exec(
				`INSERT INTO nodes (id, parent_id, name, kind, size, mtime, record) VALUES (?, ?, ?, ?, ?, ?, ?)`,
				entryID, calleesID, calleeName, 0, len(content), now, content,
			); err != nil {
				return fmt.Errorf("insert callee entry %s: %w", entryID, err)
			}
		}
	}

	return nil
}

// materializeLSP reads leyline's _lsp_hover and _lsp tables (if present)
// and creates materialized files in construct directories:
//   - {construct}/hover   (type signature / documentation from LSP hover)
//   - {construct}/diagnostics (LSP diagnostics as JSON, if any)
//
// The _lsp tables are produced by `leyline lsp --merge-db` or standalone projection.
// node_ids in _lsp use "symbols/{name}" format; we map them to existing construct
// directories by matching the symbol name to directory names in the nodes table.
//
// TODO: Replace this hardcoded materializer with a schema-driven approach.
// LSP files (hover, diagnostics, refs) should be declarable in the topology
// schema alongside tree-sitter files, e.g.:
//
//	"files": [
//	  {"name": "source", "content_template": "{{.scope}}"},
//	  {"name": "hover", "content_source": "lsp_hover"},
//	  {"name": "diagnostics", "content_source": "lsp_diagnostics"}
//	]
//
// This separates the "rules" (what each construct gets) from the "parsing"
// (how LSP/tree-sitter data is produced), matching the existing schema pattern.
func materializeLSP(tx *sql.Tx, now int64) error {
	// Check if _lsp_hover table exists
	var hoverCount int
	err := tx.QueryRow(`SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='_lsp_hover'`).Scan(&hoverCount)
	if err != nil || hoverCount == 0 {
		// No LSP data, nothing to do
		return nil
	}

	// Materialize hover text as files.
	// _lsp_hover has (node_id TEXT PK, hover_text TEXT).
	// node_ids are like "symbols/Model", "symbols/Model/memory_gb", etc.
	rows, err := tx.Query(`SELECT node_id, hover_text FROM _lsp_hover WHERE hover_text != ''`)
	if err != nil {
		return fmt.Errorf("query _lsp_hover: %w", err)
	}
	defer func() { _ = rows.Close() }()

	// Build a set of known directory node IDs for matching
	dirRows, err := tx.Query(`SELECT id FROM nodes WHERE kind = 1`)
	if err != nil {
		return fmt.Errorf("query dirs: %w", err)
	}
	dirSet := make(map[string]bool)
	for dirRows.Next() {
		var id string
		if err := dirRows.Scan(&id); err != nil {
			_ = dirRows.Close()
			return err
		}
		dirSet[id] = true
	}
	_ = dirRows.Close()

	// Build a name→dirID index for fuzzy matching (last path component)
	nameToDir := make(map[string][]string)
	for id := range dirSet {
		parts := strings.Split(id, "/")
		name := parts[len(parts)-1]
		nameToDir[name] = append(nameToDir[name], id)
	}

	for rows.Next() {
		var nodeID, hoverText string
		if err := rows.Scan(&nodeID, &hoverText); err != nil {
			return err
		}

		// Extract the symbol name from the LSP node_id
		// "symbols/Model/memory_gb" → "memory_gb"
		symbolName := nodeID
		if strings.HasPrefix(nodeID, "symbols/") {
			symbolName = strings.TrimPrefix(nodeID, "symbols/")
		}
		parts := strings.Split(symbolName, "/")
		leafName := parts[len(parts)-1]

		// Find matching construct directory
		var targetDirs []string
		if dirs, ok := nameToDir[leafName]; ok {
			targetDirs = dirs
		}

		for _, dirID := range targetDirs {
			hoverID := dirID + "/hover"

			// Check if already exists
			var exists int
			_ = tx.QueryRow(`SELECT COUNT(*) FROM nodes WHERE id = ?`, hoverID).Scan(&exists)
			if exists > 0 {
				continue
			}

			if _, err := tx.Exec(
				`INSERT INTO nodes (id, parent_id, name, kind, size, mtime, record) VALUES (?, ?, ?, ?, ?, ?, ?)`,
				hoverID, dirID, "hover", 0, len(hoverText), now, hoverText,
			); err != nil {
				return fmt.Errorf("insert hover %s: %w", hoverID, err)
			}
		}
	}
	if err := rows.Err(); err != nil {
		return err
	}

	// Materialize diagnostics from _lsp table (if it has diagnostics column)
	var lspCount int
	err = tx.QueryRow(`SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='_lsp'`).Scan(&lspCount)
	if err != nil || lspCount == 0 {
		return nil
	}

	diagRows, err := tx.Query(`SELECT node_id, diagnostics FROM _lsp WHERE diagnostics IS NOT NULL AND diagnostics != ''`)
	if err != nil {
		return nil // column might not exist in older schemas
	}
	defer func() { _ = diagRows.Close() }()

	for diagRows.Next() {
		var nodeID, diagnosticsJSON string
		if err := diagRows.Scan(&nodeID, &diagnosticsJSON); err != nil {
			continue
		}
		// Parse diagnostics JSON to verify it's valid (and not just a string error message)
		symbolName := nodeID
		if strings.HasPrefix(nodeID, "symbols/") {
			symbolName = strings.TrimPrefix(nodeID, "symbols/")
		}
		parts := strings.Split(symbolName, "/")
		leafName := parts[len(parts)-1]

		var targetDirs []string
		if dirs, ok := nameToDir[leafName]; ok {
			targetDirs = dirs
		}

		for _, dirID := range targetDirs {
			diagID := dirID + "/diagnostics"
			var exists int
			_ = tx.QueryRow(`SELECT COUNT(*) FROM nodes WHERE id = ?`, diagID).Scan(&exists)
			if exists > 0 {
				continue
			}
			// TODO: We should make this query
			if _, err := tx.Exec(
				`INSERT INTO nodes (id, parent_id, name, kind, size, mtime, record) VALUES (?, ?, ?, ?, ?, ?, ?)`,
				diagID, dirID, "diagnostics", 0, len(diagnosticsJSON), now, diagnosticsJSON,
			); err != nil {
				return fmt.Errorf("insert diagnostics %s: %w", diagID, err)
			}
		}
	}

	return nil
}

// extractCallerDir gets the construct directory from a node_id.
// "pkg/functions/FuncA/source" -> "pkg/functions/FuncA"
// "pkg/functions/FuncA" -> "pkg/functions/FuncA"
//
// NOTE: The set of leaf names checked here (source, context, doc, callers,
// callees) is coupled to the leaf naming conventions used by the schema and
// the virtual directory materializers. If new leaf types are added, this
// function must be updated to match.
func extractCallerDir(nodeID string) (dirID string) {
	// Find the last slash. If there isn't one, mimic the original behavior
	// of returning an empty string.
	idx := strings.LastIndexByte(nodeID, '/')
	if idx < 0 {
		return dirID
	}

	// Use a switch for a clean, readable multi-match
	switch last := nodeID[idx+1:]; last {
	case "source", "context", "doc", "callers", "callees", "hover", "diagnostics":
		// Return the string up to (but not including) the last slash
		dirID = nodeID[:idx]
	default:
		dirID = nodeID
	}
	return dirID
}

// extractFuncName pulls the function name from a node path like "functions/Foo/source".
// Returns the second-to-last path component (the function directory name).
func extractFuncName(nodeID string) string {
	// "functions/ProcessOrder/source" -> "ProcessOrder"
	// "types/MyStruct/source" -> "MyStruct"
	parts := strings.Split(nodeID, "/")
	if len(parts) < 2 {
		return ""
	}
	return parts[len(parts)-2]
}
